### ISSUE TITLE
[RFC] Rename repository?

### ISSUE THREAD

**Issue by stweil** [OCR-D/core#1000]
The current repository name `core` is very generic (thousands of unrelated repositories have that name).

I think it would be good to rename it to a more specific name like for example `ocrd_core`.

**Comment by bertsky** [comment]
I disagree. Short is king. Context OCR-D is clear. Forks can rename, if they want.

Besides, we have used that name in so many places (documents, presentations, repos). It would just cause confusion. And take a lot of extra work – which we already have plenty of.

**Comment by kba** [comment]
Yeah, agree with @bertsky, `OCR-D/core` is short and sweet, used everywhere now and we have no need of a further source of problems.
