### ISSUE TITLE
Inconsistent CLI parameters of ocrd resmgr

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/core#1016]
It is
```
ocrd resmgr download ocrd-example-processor
```
but:
```
ocrd resmgr list-available -e ocrd-example-processor
```

(requires an additional `-e`)

**Comment by kba** [comment]
It's because for `download` you MUST specify the processor (or use `*` explicitly for all resources of all processors) so it is an argument and not an option, whereas for `list-available`, the default is all processors and can be narrowed down to a specific processor with `-e`.
