### ISSUE TITLE
expose version according to PEP 396

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#1040]
[PEP 396](https://www.python.org/dev/peps/pep-0396/) says we should export a `__version__` attribute.

**Comment by kba** [comment]
> This PEP was formally rejected on 2021-04-14. The packaging ecosystem has changed significantly in the intervening years since this PEP was first written, and APIs such as importlib.metadata.version() [11] provide for a much better experience.

It already seems to work as it's supposed to:

```python
from importlib.metadata import version # python >= 3.8
from importlib_metadata import version # python <= 3.7
version('ocrd')
'2.49.0'
```

**Comment by bertsky** [comment]
> It already seems to work as it's supposed to:
> 
> ```python
> from importlib.metadata import version # python >= 3.8
> from importlib_metadata import version # python <= 3.7
> version('ocrd')
> '2.49.0'
> ```

That's not what PEP 396 says, though. You are using [distribution package](https://packaging.python.org/en/latest/glossary/#term-Distribution-Package) metadata, specifically the version specifier from [PEP-440](https://peps.python.org/pep-0440/).

**Comment by kba** [comment]
> This PEP was formally rejected on 2021-04-14.

Then there's [PEP 386](https://peps.python.org/pep-0386/) which is superseded by [PEP 440](https://peps.python.org/pep-0440).

I don't have a problem with adding `__version__` in principle, but would it be enough to do

```
# in e.g. ocrd/ocrd/__init__.py
from ocrd_utils.constants import VERSION
__version__ = VERSION
```

or would we need to hard-code the version?

**Comment by bertsky** [comment]
> > This PEP was formally rejected on 2021-04-14.
> 
> Then there's [PEP 386](https://peps.python.org/pep-0386/) which is superseded by [PEP 440](https://peps.python.org/pep-0440).

oh, I missed that, sry.

ok, you're right – we already have two ways to get the version, that should suffice.
