### ISSUE TITLE
[feature request] Enhance `ocrd workspace bulk-add` to add URL entries instead of files

### ISSUE THREAD

**Issue by stweil** [OCR-D/core#1086]
`ocrd workspace bulk-add` can be used to add ALTO XML files to an existing METS file (see [example](https://github.com/UB-Mannheim/tudigi-gt/wiki)). The new entries refer to the local files which were added, but for the production use on a web server the METS file must contain a URL for each ALTO XML file. So after running the `ocrd` command, additional processing like in the example is required. It would be nice if that additional processing could be avoided.

**Comment by kba** [comment]
Good point. I need to fix the bulk-add mechanism to be compatible with #1079, I'll implement in such a way, that it will be possible to set both the local filename and remote URL.

**Comment by stweil** [comment]
It took some time, but now I could use the new code in a real use case. Running `ocrd bulk-add` works fine as long as I provide both `--url`  and `--local-filename` arguments. It then writes two `mets:FLocat` entries for each page, one with the file path and one with the URL. As the presentation only needs the URL, but not the file path, I then tried running the command without a `--local-filename` argument. I had expected that it would write only the desired `mets:FLocat` entry with the URL, but it wrote again the other entry, too – in this case with a completely unusable file path:
```
    <mets:fileGrp USE="FULLTEXT">
      <mets:file ID="file-alto-idp251240016" MIMETYPE="text/xml">
        <mets:FLocat xlink:href="      &lt;mets:div ID=&quot;struct-physical-idp251240016&quot; CONTENTIDS=&quot;http:/diglib.hab.de/drucke/li-1876-1/start.htm?image=00001&quot; TYPE=&quot;page&quot; ORDER=&quot;1&quot;&gt;" LOCTYPE="OTHER" OTHERLOCTYPE="FILE"/>
        <mets:FLocat xlink:href="https://ub-backup.bib.uni-mannheim.de/~stweil/d-gt/data/DE-23/urn_nbn_de_gbv_23-drucke_li-1876-12/alto/00001.xml" LOCTYPE="URL"/>
      </mets:file>
    [...]
```

Would it be reasonable to change that, so that only a URL entry is added if only the `--url` argument is given?

**Comment by bertsky** [comment]
Note: you can do that with [mm-update](https://github.com/slub/mets-mods2tei#mm-update), too. (It's what we use in the [OCR-D Manager](https://github.com/slub/ocrd_manager/blob/d6cf314edbfc2df44382036683edd4b5404e2501/ocrd_lib.sh#L224-L249).

But I am also for more flexibility of bulk-add. Also mentioned in https://github.com/OCR-D/core/issues/1150. (And somewhat related: https://github.com/OCR-D/core/issues/1179.)

**Comment by stweil** [comment]
@kba, I recently used the bulk-add again with latest `ocrd`. It still adds two `mets:FLocat` for URL and local file although I only need the URL. That's a minor issue, but it would still be nice to have this fixed.
