### ISSUE TITLE
DockerHub releases do not have versioned tags anymore

### ISSUE THREAD

**Issue by kba** [OCR-D/core#1092]
The last versioned release was [v2.47.4](https://hub.docker.com/layers/ocrd/core/v2.47.4/images/sha256-f42a743177e255bd32e782fc9a18e1515f34d1434b74b7beec6fd7ce5a34c1b2?context=explore), we do generate `latest` from master but not for the releases.

**Comment by kba** [comment]
I will rebuild, tag and push manually now and fix the CI afterwards, so you are able to update asap.

**Comment by kba** [comment]
It's now fixed, both the Dockerhub and GHCR images are properly tagged automatically. Thanks for the reminder @markusweigelt

**Comment by kba** [comment]
And we will use tagged releases as the base for ocrd_all from now on, to make them easier to debug.

**Comment by markusweigelt** [comment]
Nice and thank you very much for the quick response. In the version overview, there are a few versions in between that look somewhat cryptic, e.g., 'v2.57.0-1-g9a3bc0e5.' What about those? Can they be used? Are those bugfix versions?

**Comment by kba** [comment]
> Nice and thank you very much for the quick response. In the version overview, there are a few versions in between that look somewhat cryptic, e.g.`v2.57.0-1-g9a3bc0e5`. What about those? Can they be used? Are those bugfix versions?

They were the states of master in between releases (version + commit hash). Since 2.57.2, releases should only be deployed for tagged commits. I will remove them from DockerHub.
