### ISSUE TITLE
Error starting "bashlib-worker"

### ISSUE THREAD

**Issue by joschrew** [OCR-D/core#1119]
I tried to start a worker with bashlib (ocrd-olena) with this command (docker-compose): `ocrd-olena-binarize worker --database $MONGODB_URL --queue $RABBITMQ_URL` and I get `/build/core/ocrd/ocrd/lib.bash: line 172: ocrd__argv[log_filename]: unbound variable`.
Then I tried `ocrd-olena-binarize worker --database $MONGODB_URL --queue $RABBITMQ_URL --logfile-name something.log` and then I get:
```
Usage: ocrd network processing-worker [OPTIONS] PROCESSOR_NAME
Try 'ocrd network processing-worker --help' for help.

Error: No such option: --log-filename
```
I would just remove the `--logfile-name` thing from lib.bash again which was introduced [here](https://github.com/OCR-D/core/commit/6fc606027aee93efd60da55e70fe8967c508da2#diff-7826d88e116f00e2c0a23335b864dcce617770e57ced1877b14d5ca74748b5ea
but I don't know if that was put there with something in mind.

**Comment by MehmedGIT** [comment]
#1120 fixes it.
