### ISSUE TITLE
regression in core 2.63.0

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#1190]
ocrd --version

produces:
```
ImportError: cannot import name 'DEFAULT_METS_BASENAME' from 'ocrd_utils' (/data/ocr-d/ocrd_all/venv38/lib/python3.8/site-packages/ocrd_utils/__init__.py
```

**Comment by kba** [comment]
I cannot reproduce, `ocrd --version` works fine for me with both editable and normal install.

One source of this might be old `ocrd_...` packages.

Can you try

```
pip uninstall ocrd{,_models,modefactory,utils,network,validators}
make install
```

and check whether that solves it?

**Comment by bertsky** [comment]
Sorry, cannot reproduce either now (and don't remember under what circumstances this happened)...

**Comment by bertsky** [comment]
Found another instance:
```
python -c "from ocrd_models.ocrd_file import ClientSideOcrdFile"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'ClientSideOcrdFile' from 'ocrd_models.ocrd_file' (/data/ocr-d/ocrd_all/venv38/sub-venv/headless-tf1/lib/python3.8/site-packages/ocrd_models/ocrd_file.py)
```

So indeed, the cause seems to be older installations of the other top-level modules _as packages_:
```
$ pip show ocrd
Name: ocrd
Version: 2.63.0
$ pip show ocrd_models
Name: ocrd-models
Version: 2.52.0
```
To repair the venv, I had to do `pip uninstall ocrd_{models,modefactory,utils,network,validators}`  – both in the sub-venv and the top venv.

IMO we can close – users can still find it by searching the issue.
