### ISSUE TITLE
ocrd workspace find yields error without -k parameter

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#130]
```
ocrd workspace find
Usage: ocrd workspace find [OPTIONS]

Error: Invalid value for "-k" / "--output-field": invalid choice: u. (choose from url, mimetype, groupId, ID, basename, basename_without_extension, local_filename)
```
(other commands do work though)

**Comment by lschiffer** [comment]
The problem lies probably in the following lines:
> https://github.com/OCR-D/core/blob/268f5fcb2aa52bd424d3e02e44e8a9995b0bed96/ocrd/cli/workspace.py#L151-L153
The default value 'url' seems to be treated as a list ['u', 'r', 'l'] of multiple parameters, causing the invalid parameter 'u' .

**Comment by kba** [comment]
Thanks, fixed.
