### ISSUE TITLE
cache_enabled

### ISSUE THREAD

**Issue by finkf** [OCR-D/core#143]
Maybe it is better to default cache_enabled to false. 
If one needs the extra speedup one can enable it manually.
Its weird during development if changes are not visible :)

**Comment by finkf** [comment]
see #132

**Comment by kba** [comment]
Caching was purely for practical reasons, transmitting image files via mobile network before I had high speed internet available. I'll fix this next, thanks for reminding.

**Comment by kba** [comment]
fixed (caching removed) in v0.5.0
