### ISSUE TITLE
Broken link in http://www.ocr-d.de/sites/all/GTDaten/IndexGT.html

### ISSUE THREAD

**Issue by finkf** [OCR-D/core#168]
The [Ground-Truth-Daten](http://www.ocr-d.de/sites/all/GTDaten/IndexGT.html) page contains a broken link.

The link of `benner_herrnhuterey04_1748` links to http://www.ocr-d.de/sites/all/GTDaten/arnimb_goethe03_1835.zip

It should link to http://www.ocr-d.de/sites/all/GTDaten/benner_herrnhuterey04_1748.zip (which exists)

**Comment by ehrmn** [comment]
Thank you. Fixed the link and updated the file now.
