### ISSUE TITLE
Missing coordinates in benner_herrnhuterey04_1748

### ISSUE THREAD

**Issue by finkf** [OCR-D/core#169]
The [benner_herrnhuterey04_1748](http://www.ocr-d.de/sites/all/GTDaten/benner_herrnhuterey04_1748.zip) archive contains a line `id="line_1475763813937_156"` with empty line-coordinates in the `page/*0013.xml` PAGE-XML file.

**Comment by tboenig** [comment]
The bug is fixed. A new version can be downloaded.
