### ISSUE TITLE
TypeError: Arguments take exactly one parameter declaration, got 2

### ISSUE THREAD

**Issue by seuretm** [OCR-D/core#186]
Hello,

I'm encountering some issue with the Python API. It worked fine during the meeting in Berlin, a few months ago. As I've now a satisfiable initial version of a font classifier, I plan to integrate it, so I started reading documentation about how to do it properly. I tried again to run the API, after having installed the latest version, but am however not able to make it run anymore. When I run `ocrd --version`, I get the error message given in the title.

I'll first provide a few information about versions and installation procedures, and then some logs.

If anybody has an idea about what's going wrong, and how to solve this issue, this would be helpful. If it is due to me having too recent libraries/software, then we can assert that other persons will have this problem too later. I hope it is not the case.

**Software versions**
I'm running an up-to-date Archlinux, so all packages are typically the latest stable version available.
- Python 2.7.15, 3.7.0, and 3.6.6 (I tried all three of them)
- python-pip 18.0-1 (same version for Python 2 and Python 3)
- python-virtualenv 16.0.0-1 (same version for Python 2 and Python 3)
- make 4.2.1-2 (latest, based on http://ftp.gnu.org/gnu/make/)

The following libraries are installed by pip along with ocrd:
- ocrd-0.8.5-py3-none-any.whl
- jsonschema-2.6.0-py2.py3-none-any.whl
- Flask-1.0.2-py2.py3-none-any.whl
- Deprecated-1.2.0-py2.py3-none-any.whl
- Pillow-5.3.0-cp37-cp37m-manylinux1_x86_64.whl
- **Click-7.0-py2.py3-none-any.whl** (the error is raised from this lib)
- opencv_python-3.4.3.18-cp37-cp37m-manylinux1_x86_64.whl
- lxml-4.2.5-cp37-cp37m-manylinux1_x86_64.whl
- requests-2.19.1-py2.py3-none-any.whl
- numpy-1.15.2-cp37-cp37m-manylinux1_x86_64.whl
- Jinja2-2.10-py2.py3-none-any.whl
- Werkzeug-0.14.1-py2.py3-none-any.whl
- idna-2.7-py2.py3-none-any.whl
- urllib3-1.23-py2.py3-none-any.whl
- certifi-2018.8.24-py2.py3-none-any.whl
- chardet-3.0.4-py2.py3-none-any.whl

**Installation**
With Python 3.7, I tried the installation using pip and using the repository. In both cases, I tried it first in a virtual environment, and then as root. With the two other versions of Python, I tried only in a virtual environment. There is no error message during the installation, everything goes smoothly.
I also tried to checkout from github the version of ocrd that was running in Berlin, and I still get the same issue.

**Running**
`$ ocrd --version`
`Traceback (most recent call last):`
`  File "/tmp/ocrd-venv3/bin/ocrd", line 7, in <module> from ocrd.cli import cli`
`  File "/tmp/ocrd-venv3/lib/python3.7/site-packages/ocrd/cli/__init__.py", line 3, in <module> from ocrd.cli.ocrd_tool import ocrd_tool_cli`
`  File "/tmp/ocrd-venv3/lib/python3.7/site-packages/ocrd/cli/ocrd_tool.py", line 27, in <module> @click.pass_context`
`  File "/tmp/ocrd-venv3/lib/python3.7/site-packages/click/decorators.py", line 151, in decorator _param_memo(f, ArgumentClass(param_decls, **attrs))`
`  File "/tmp/ocrd-venv3/lib/python3.7/site-packages/click/core.py", line 1808, in __init__ Parameter.__init__(self, param_decls, required=required, **attrs)`
`  File "/tmp/ocrd-venv3/lib/python3.7/site-packages/click/core.py", line 1338, in __init__ self._parse_decls(param_decls or (), expose_value)`
`  File "/tmp/ocrd-venv3/lib/python3.7/site-packages/click/core.py", line 1841, in _parse_decls 'parameter declaration, got %d' % len(decls))`
`TypeError: Arguments take exactly one parameter declaration, got 2`

For info, I've had a look at what's in `decls` briefly before line 1841: `('json_file', 'ocrd-tool.json to operate on')`

Any hint will be much appreciated.

**Comment by kba** [comment]
From a quick google search, it seems to be a click 7 issue, which has changed signatures for the method decorators (https://github.com/tmux-python/tmuxp/issues/433 https://github.com/pallets/click/issues/1128)

I will investigate further to make our code forward compatible.

In the meantime, can you try `pip install click<7` to force the earlier version?

**Comment by seuretm** [comment]
Hello,
Thank you for your answer. I replaced `pip install ocrd` by `pip install ocrd 'click<7'` and `ocrd --version` now works fine. I did not know that pip can install older versions of libraries; that is a nice feature.
