### ISSUE TITLE
anyOCR - Where is the source code?

### ISSUE THREAD

**Issue by amitdo** [OCR-D/core#203]
Hi,

This open source software was mentioned in a few papers, but I didn't find the source code.
Can you help me?

**Comment by kba** [comment]
The colleagues from DFKI are still clearing copyright and publishing procedures for preprocessing scripts IIUC. I don't know whether anyOCR as such will be released though the code I have seen are scripts that extend upstream ocropy.

@mmreza79

**Comment by amitdo** [comment]
Ok, thanks.

**Comment by kba** [comment]
@amitdo https://github.com/syedsaqibbukhari/docanalysis

**Comment by amitdo** [comment]
The license is Apache 2.0.

They added cropping to ocropy.

Thanks again!

**Comment by tawanda263** [comment]
was looking for it too.

**Comment by kba** [comment]
https://github.com/syedsaqibbukhari/docanalysis
