### ISSUE TITLE
Random segfaults with Pillow 6.0.0

### ISSUE THREAD

**Issue by kba** [OCR-D/core#238]
As discussed in [the chat](https://gitter.im/OCR-D/Lobby), using Pillow 6.0.0 will lead to random segfaults when using the TiffImagePlugin. It's inconsistent, so there might be a race condition somewhere in Pillow code.

For now we require `Pillow < 6.0.0` but this should be properly fixed.

**Comment by mikegerber** [comment]
Apparently the reproducer for this can be found here: https://github.com/OCR-D/core/issues/270#issuecomment-519183163

**Comment by kba** [comment]
We've moved to >= 6.2.0 throughout.
