### ISSUE TITLE
update XML namespace in PAGE model

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#242]
There are currently two distinct places where the PAGE schema version is defined:

1. in the [output of generateDS](https://github.com/OCR-D/core/blob/589fcdf0d54fa7db14d1c273deecdfc9a24fdfff/ocrd_models/ocrd_models/ocrd_page_generateds.py#L9441), which uses `2018-07-15`
2. in a [constant used for `to_xml`](https://github.com/OCR-D/core/blob/589fcdf0d54fa7db14d1c273deecdfc9a24fdfff/ocrd_models/ocrd_models/constants.py#L14), which is still `2017-07-15`

They are not in agreement! Also, this should not be allowed to happen (i.e. generateDS should be called with the version from constants.py). 

And I think we already depend on 2018 features.

Possibly related to #67.

**Comment by mikegerber** [comment]
One such feature is `MetadataItem`: This element was introduced in PAGE 2018-07-15, but e.g. `ocrd-tesserocr-recognize` produces a `2017-07-15` XML that includes this item and so is invalid. Thus, PAGE Viewer refuses to open it.

**Comment by bertsky** [comment]
@mikegerber Yes, but there are (usually) more offenders (`RelationType/@id`, `PageType/@imageXResolution`, `PageType/@imageYResolution`, `SourceRegionRef` vs `RegionRef` etc). You can remove `MetadataItem` with this stylesheet:

```xsl
<xsl:stylesheet
    version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:pc="http://schema.primaresearch.org/PAGE/gts/pagecontent/2017-07-15">
  <xsl:output
      method="xml"
      standalone="yes"
      encoding="UTF-8"
      omit-xml-declaration="no"/>
  <xsl:template match="pc:PcGts/pc:Metadata/pc:MetadataItem"/>
  <xsl:template match="node()|text()|@*">
    <xsl:copy>
      <xsl:apply-templates select="node()|text()|@*"/>
    </xsl:copy>
  </xsl:template>
</xsl:stylesheet>
```
(e.g. with xsltproc) and try again, but the simplest workaround (until core gets fixed) would be to just replace the version string in the files:

```bash
sed -i 's,2017-07-15,2018-07-15,g' filename
```

**Comment by mikegerber** [comment]
For anyone else having this problem, this is the fix script I use now:

~~~
#!/bin/sh
for x in OCR-D*/*; do
  if file --brief --mime "$x" | grep -q '^text/xml'; then
    sed -i 's#pagecontent/2017-07-15#pagecontent/2018-07-15#g' "$x"
  fi
done
~~~

**Comment by kba** [comment]
We will use the upcoming 2019-07-15 version throughout.

**Comment by wrznr** [comment]
Cf. #67

**Comment by kba** [comment]
Implemented in https://github.com/OCR-D/core/pull/267
