### ISSUE TITLE
extend PAGE validator with geometry heuristics

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#252]
We should have heuristics to check for

- polygon containment (overlapping regions, word outside line etc.)
- artifacts from annotation like point or line-like regions
- lines with (way) too much whitespace (bad cropping, or bad segmentation)
- probably even: missing `@orientation`

_Originally posted by @kba in https://github.com/OCR-D/assets/issues/28#issuecomment-505369910_

**Comment by bertsky** [comment]
BTW, `shapely.geometry.polygon.Polygon` has very nice API for the first 2 tasks, including `contains()` and `area()`. 

The third could be achieved with ad-hoc binarization and some simple Numpy statistics like `count_nonzero()` (i.e. pixel-counting), or `nonzero()` followed by `amin()` and `amax()` to get non-white bounds (i.e. area-counting).

And orientation checking could be done in a similar way like deskewing (i.e. entropy based), but with some kind of confidence measure.

**Comment by bertsky** [comment]
A good reference for additional checks are the validation error classes in [Aletheia](https://www.primaresearch.org/www/assets/tools/Aletheia%20User%20Guide.pdf), p. 118/119.

**Comment by kba** [comment]
c.f. https://github.com/OCR-D/ocrd_evaluate_segmentation

**Comment by bertsky** [comment]
> c.f. https://github.com/OCR-D/ocrd_evaluate_segmentation

now renamed to https://github.com/OCR-D/ocrd_segment (there will be more processors)

**Comment by kba** [comment]
https://github.com/OCR-D/ocrd_segment is a better place for this.
