### ISSUE TITLE
Improve package docstrings

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#254]
IMO the core packages (`ocrd`, `ocrd_models` etc) should really use package-level docstrings (i.e. top-level docstrings in `__init__.py` in each directory) to aid browsing the implementation from Python (or with a browser in the generated apidoc). Also, the main `README.md` should not call these "modules" but "packages".

**Comment by kba** [comment]
Fixed by https://github.com/OCR-D/core/pull/292
