### ISSUE TITLE
Add a real logging level "trace"

### ISSUE THREAD

**Issue by wrznr** [OCR-D/core#255]
AFAICS, `TRACE` is simply mapped to `DEBUG`. It would be great to have a distinct output granularity level trace (e.g., for glyph-related messages which may cause huge amounts of log messages).

**Comment by kba** [comment]
The need for `TRACE` like `FINE`, `FINER`, `FINEST` (Java) or `silly` (Node.JS) are a sign that your `DEBUG` statements should probably be `INFO` or disabled.

It is possible to define a custom level with a lower priority than `DEBUG` but Python [logging docs](https://docs.python.org/3/howto/logging.html#custom-levels) says this about custom levels.

> if you are convinced that you need custom levels, great care should be exercised when doing this, and it is possibly a very bad idea to define custom levels if you are developing a library. That’s because if multiple library authors all define their own custom levels, there is a chance that the logging output from such multiple libraries used together will be difficult for the using developer to control and/or interpret, because a given numeric value might mean different things for different libraries.

Also you cannot use the convenience methods like `log.trace(msg)` but must use `log.log(TRACE, msg)`.

That being said, it wouldn't be hard to implement if you think it's useful.

**Comment by wrznr** [comment]
Fine with me to close this issue. Much more important would be general recommendations what should be logged where. The single processors are highly diverse in this respect. Maybe even a point for specs.

**Comment by kba** [comment]
> Maybe even a point for specs.

Maybe @VolkerHartmann can address this in https://github.com/OCR-D/spec/blob/master/logging.md?
