### ISSUE TITLE
ocrd_exif JPEG resolutionUnit is but an integer

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#256]
in `ocrd_models.OcrdExif`, there is an abstraction `resolutionUnit` across all file formats. But for JPEGs, since [Pillow](https://github.com/python-pillow/Pillow/blob/1c57a41ececc4529520a423b9bec13c78927cb25/src/PIL/JpegImagePlugin.py#L86) does not convert `jfif_unit` from integer to string, we get `1` instead of `inches` and `2` instead of `cm`. See [JFIF tag spec](https://sno.phy.queensu.ca/~phil/exiftool/TagNames/JFIF.html). 

What's more, I think we should get a contract here in form of a class, say `OcrdExif.UNIT` which enumerates all allowed values as members, i.e. `OcrdExif.UNIT.inch`, `OcrdExif.UNIT.cm` etc.

**Comment by kba** [comment]
> What's more, I think we should get a contract here in form of a class, say OcrdExif.UNIT which enumerates all allowed values as members, i.e. OcrdExif.UNIT.inch, OcrdExif.UNIT.cm etc.

From a software architect's POV that's the right move. I would however favor not having the resolutionUnit as part of the logic at all and convert dpcm to dpi consistently.

BTW: meaning of the jfif_unit tag:

* 0: no unit
* 1: inches
* 2: cm

**Comment by bertsky** [comment]
>  I would however favor not having the resolutionUnit as part of the logic at all 

Yeah, it's probably enough to just have a docstring.

> and convert dpcm to dpi consistently.

I saw that in your TODO comment. But then why have a `resolutionUnit` in the first place? And since conversion might introduce rounding errors, I would prefer keeping the pair value + unit (as does PAGE).

**Comment by kba** [comment]
> why have a resolutionUnit in the first place?

That was my question, yes. But you're right, better to keep in line with PAGE and retain the original units. Requires implementers to be as meticulous as you are when accessing resolution (e.g. https://github.com/OCR-D/ocrd_tesserocr/pull/54/commits/e9c95ba985994fa6d60d29c83ebb762f377bd112#diff-211e1e250fddd7a8b652c4fa8838dd02R93). But fine with me if fine with you.

**Comment by bertsky** [comment]
Fine with me! (We can still do the inch recalculation inside `OcrdExif` in the future if we feel it's necessary, without breaking callers. Especially if file formats want to offer typographic dots etc.)
