### ISSUE TITLE
PAGE validator: show physical pageId or METS file ID

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#259]
The METS-related validators all show the `mets:file/@ID` of the incriminated page. But the PAGE validator does not: it just points to the ID of the element on the page. So there is no way in knowing what file it relates to (as PAGE identifiers need not be unique across files), and it is _very_ inconvenient.

Mitigation will not be simple: `PageValidator` does not necessarily know the `OcrdFile` which the page originated from, and `PageType` has no ID and `pcGtsId` is usually empty or unrelated.

IMO, at least when calling `PageValidator.validate` from the workspace validator the file id or page id should be passed in, and used in the error description.

**Comment by kba** [comment]
As you say, this would be tricky for the standalone PAGE validator but when called in the context of the METS file referencing it, page ID can be passed to the constructor and output in the logs.

**Comment by bertsky** [comment]
Is it just me, is no-one else constantly looking at these failed reports and wondering where the hell they come from? Probably everyone got used to running with most checks disabled anyway?

**Comment by bertsky** [comment]
Fixed by #374
