### ISSUE TITLE
Processor does not allow to add cli options

### ISSUE THREAD

**Issue by n00blet** [OCR-D/core#260]
currently it is not possible to add cli arguments.
If we add new click.options to the cli wrapper for the processor, then this argument is not passed to the processor. instead we get a error message 
`TypeError: run_processor() got an unexpected keyword argument 'keyword'`

**Comment by kba** [comment]
To keep the CLI uniform, it is preferable to implement additional flags and options as parameters in the `ocrd-tool.json` over extending the CLI.
