### ISSUE TITLE
"prune-files" command

### ISSUE THREAD

**Issue by kba** [OCR-D/core#272]
We have this use case:

  * Start with  fully manifested workspace with some files to be fixed
  * Delete all the files not related to this fix
  * Fix files
  * Reduce mets.xml to only the changed files, i.e.
    * For every mets:file: Does it exist on hdd?
    * If no: delete the mets:file and mets:fptr to that mets:file
  * Remove empty file groups and empty pages in mets.xml

@tboenig Did I get that right?

**Comment by tboenig** [comment]
@kba that's ok. 
``For every mets:file: Does it exist on hdd?`` I think the mets:file in the directory or the specified file in the commandline.

**Comment by kba** [comment]
> I think the mets:file in the directory or the specified file in the commandline.

Yeah, the path of the mets:file relative to the mets.xml must exist.

**Comment by tboenig** [comment]
yes

**Comment by kba** [comment]
Implemented in 20f62da
