### ISSUE TITLE
output_file_grp not set to ocrd-tool.json default for processors

### ISSUE THREAD

**Issue by kba** [OCR-D/core#274]
e.g.

```yaml
{
  output_file_grp: "OCR-D-IMG-BIN",
}
```

but in processor's `process` method:

```python
print(self.output_file_grp)
```

prints `OUTPUT` not `OCR-D-IMG-BIN`.

**Comment by kba** [comment]
@crater2150 reports the same problem for `input_file_grp`

**Comment by kba** [comment]
Related https://github.com/OCR-D/ocrd_tesserocr/pull/75/files#r321639953

> But I agree with you all these errors should be reported properly and as early as possible. So either the Processor base class or process_cli / ocrd_cli_wrap_processor should check in ocrd-tool for the number of outputs. We discussed this in the spec, but it is not official, and not implemented yet. Also related to OCR-D/core#296.

**Comment by bertsky** [comment]
I cannot find the reference, but I think we agreed that fileGrp names listed in the ocrd-tool.json are merely examples, not fallbacks. Users _always_ have to specifiy these on the command line. So can we close this?

**Comment by kba** [comment]
>  I think we agreed that fileGrp names listed in the ocrd-tool.json are merely examples,

https://github.com/OCR-D/spec/pull/121

 `-I/-O` is currently only required in bashlib, the Python `Processor` implementations still have fallbacks (`INPUT`/`OUTPUT`). Once those are gone, this can be closed.
