### ISSUE TITLE
generated namespace prefix is invalid

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#277]
With `1.0.0b12`, I now get documents from `to_xml` that begin like this:
```XML
<pc:PcGts xmlns="http://schema.primaresearch.org/PAGE/gts/pagecontent/2019-07-15">
```

Thus, all elements use the `pc` prefix, but this is not declared in the root as `xmlns:pc=...`. 

IMO, this regression is a combination of c0c1ea6ac9a20228fe07f2c3c1d741c4a07b2475 and the earlier af5098da – first `to_xml` was rewritten to not include the `pc` prefix anymore (but at that time it was also not used in the generateDS call), then the generateDS call changed (but `to_xml` was not changed back accordingly).

**Comment by bertsky** [comment]
Oh, I just found your fix 22a46248414d404664d8ec465214444b73c6b7ab

**Comment by bertsky** [comment]
(Could we separate this out of #268, and merge right away?)

**Comment by n00blet** [comment]
@kba hi, can you please fix this ?

**Comment by kba** [comment]
Fixed in 1.0.0b15

**Comment by bertsky** [comment]
Thanks!

**Comment by dstoekl** [comment]
what is the purpose of the pc prefix? e.g. pc:pcgts? It does not validate against the schema.

**Comment by cneud** [comment]
> what is the purpose of the pc prefix? e.g. pc:pcgts? It does not validate against the schema.

`pc` stands for `page content` within PAGE-XML afaict. The [PAGE schema](https://www.primaresearch.org/schema/PAGE/) also has various other parts, e.g. relating to evaluation of binarization etc.

**Comment by dstoekl** [comment]
thx. but why would you prefix every single namespace with it? I haven't seen this on other pagexmls and it does not validate against the schema given.

**Comment by kba** [comment]
> thx. but why would you prefix every single namespace with it? I haven't seen this on other pagexmls and it does not validate against the schema given.

Why would this not validate against the PAGE schema? Our PAGE-XML define `xmlns:pc=xmlns="http://schema.primaresearch.org/PAGE/gts/pagecontent/2019-07-15"` so this should be valid. If we produce invalid XML, please open a new issue and share the setup that led to the faulty PAGE-XML.

**Comment by dstoekl** [comment]
ok. never mind.
