### ISSUE TITLE
mets:file/mets:FLocat requires @LOCTYPE

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#310]
With current ocrd_mets, add_file does not write the `LOCTYPE` attribute anymore. But this is required by the METS XSD. I believe, `OTHER` is the only appropriate value for relative filesystem paths (with `OTHERLOCTYPE` suggested but not required to be set as well).

**Comment by kba** [comment]
I think that's not a regresssion ("anymore"), we never did this. I think I haven't validated our METS as well as I should have.

Will fix.
