### ISSUE TITLE
No file extensions for bagged workspaces

### ISSUE THREAD

**Issue by tboenig** [OCR-D/core#332]
I believe the bag feature from ocrd makes errors in mets-files. I miss the files extension. You can see this on my example.

```xml
<mets:file ID="OCR-D-GT-SEG-PAGE_0003" MIMETYPE="application/vnd.prima.page+xml">
<mets:FLocat xlink:href="OCR-D-GT-SEG-PAGE/OCR-D-GT-SEG-PAGE_0003" LOCTYPE="URL"/>
```

**Comment by kba** [comment]
To clarify: The problem is two-fold:

1) When bagging a file without extension, no extension will be added
2) Extensions are added to the actual file on the actual file system but not in the xlink:href in some, to be determined, circumstances.

**Comment by kba** [comment]
The problem here was an outdated version of `core`.

I have a fix for 1) with https://github.com/kba/ocrd-core/commit/0a871ea9f55eaeef6001370d6860f35919f15d58 but I am not sure about the ramifications so I am reluctant to integrate it until we have a real use case.
