### ISSUE TITLE
docker: revert to ubuntu:18.04

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#344]
Dockerfile for `ocrd/core` recently changed from `FROM ubuntu:18.04` to `FROM ubuntu:19.10`. This creates problems with Olena build, e.g. because Ubuntu changed its default C toolchain from GCC 7 to 9, and automake 1.16 broke some existing API or conventions over 1.15.

Moreover, the [spec](https://ocr-d.github.io/docker) still states Ubuntu 18.04 as the baseline. And we have good reasons to keep it at that for a while: Because modules have already hand-crafted their system dependencies into package lists for that distro (`make deps-ubuntu` etc). 

Given that Travis still runs Ubuntu 14.04, I don't think we should rush from one (not even LTS) version to the next, creating unnecessary inompatibilities / workload in the modules.

**Comment by kba** [comment]
> Given that Travis still runs Ubuntu 14.04, I don't think we should rush from one (not even LTS) version to the next, creating unnecessary inompatibilities / workload in the modules.

The main reason for having the most recent Ubuntu release as the base was the more recent tesseract libraries. But since that causes problems elsewhere, I agree to downgrade it to 18.04 LTS and keep it there. I'll update the ocrd_tesserocr Dockerfile accordingly as well.

**Comment by bertsky** [comment]
Splendid, thanks!
