### ISSUE TITLE
Docker: base on CUDA/cuDNN Ubuntu variants?

### ISSUE THREAD

**Issue by kba** [OCR-D/core#346]
@mikegerber mentioned that in order to use the CUDA GPU API in Docker, basing on NVIDIA's Ubuntu base images might be necessary.

As we are going to revert 19.10 -> 18.04 LTS (#344) it would be a good moment to switch to something GPU-friendly.

* Is this going to be a license issue, i.e. will the images be Apache 2.0 licensed?
* Will this negatively impact performance (beyond bigger container images)?
* Which version for 18.04 should we use?

@bertsky @mikegerber @finkf @wrznr

**Comment by bertsky** [comment]
I'll add:
 - Can we get this fully optional w.r.t. CUDA requirements for the host? (I.e. will it be possible to at least run the non-CUDA parts on a host without CUDA toolkit and drivers or even GPU hardware.)

So far, I would doubt it. From [nvidia-docker](https://github.com/NVIDIA/nvidia-docker/wiki/Motivation):

> Requires only the NVIDIA driver to be installed on the host

**Comment by kba** [comment]
Let's cross that bridge when we get there.
