### ISSUE TITLE
bashlib: expose validators

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#353]
It would be very useful for OCR-D shell wrappers and non-OCR-D use-cases alike for core's bashlib to expose the various existing functions in `ocrd_validators` as separate CLI commands (i.e. not just on the workspace as a whole). For example:

```sh
ocrd validate parameters paramfile.json ocrd-tool.json
ocrd validate page [--strictness level] page.xml
```

This could also delegate to existing commands in the other action groups (for convenience):

```sh
ocrd validate ocrd-tool ocrd-tool.json
ocrd validate workspace [-s tests] [--page-strictness level] mets.xml
ocrd validate process [-m mets] command1 command2 ...
ocrd validate zip [options] source
```

**Comment by bertsky** [comment]
Also: Offer restricting the workspace validator to a subset of file groups.

**Comment by kba** [comment]
> Also: Offer restricting the workspace validator to a subset of file groups.

#383

**Comment by kba** [comment]
A dedicated `validate` CLI is a useful addition and more intuitive than e.g. the infamous

`ocrd ocrd-tool ocrd-tool.json validate`

:)

Should be simple to implement.

**Comment by kba** [comment]
Implemented and released in https://github.com/OCR-D/core/releases/tag/v2.3.0
