### ISSUE TITLE
workspace bagger: allow filtering file groups

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#356]
I know this is already [on the agenda](https://github.com/OCR-D/core/blob/76ea92710a72db278bc38fd7b698ab89b77580d1/ocrd/ocrd/workspace_bagger.py#L66), but it should be more visible IMHO: `ocrd zip bag` could really use an option that allows filtering (negatively) or selecting (positively) those file groups which to keep in the bag.

Note: This may be more difficult than it seems. There are implicit dependencies between file groups, e.g. derived images in image file groups referenced (via `AlternativeImage`) from PAGE-XML file groups.

In my makefileization, I first [`zip bag` everything](https://github.com/bertsky/workflow-configuration/blob/6e9b689979c0d5d90c67aa5d0d7421b3c2d4e401/Makefile#L188) and then [`workspace remove-group` parts](https://github.com/bertsky/workflow-configuration/blob/6e9b689979c0d5d90c67aa5d0d7421b3c2d4e401/Makefile#L252) which I don't want as a stopgap measure. But this would be much easier in Python.

**Comment by kba** [comment]
Has been implemented in #1139
