### ISSUE TITLE
bug: init create mets file

### ISSUE THREAD

**Issue by tboenig** [OCR-D/core#357]
<mets:metsHdr CREATEDATE="2019-11-22 13:50:46.528314"> <-BUG
<mets:metsHdr CREATEDATE="2019-11-22T13:50:46.528314"> <-correct (Bug fixed)

The problem is @CREATEDATE see: https://www.loc.gov/standards/mets/docs/mets.v1-9.html#metsHdr. This attribute is a xsd:dateTime. The xsd:dateTime is define ``[-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm]`` see: http://books.xmlschemata.org/relaxng/ch19-77049.html.

**Comment by wrznr** [comment]
ISO 8601

**Comment by stweil** [comment]
I think there is still a bug for months 1-9. See pull request #370 which should fix that.

**Comment by kba** [comment]
Not fixed according to @tboenig and @EEngl52

**Comment by kba** [comment]
Not a regression, the file in question was created with 2.0.0 whereas #360 which fixes this was only part of 2.0.1
