### ISSUE TITLE
ocrd: CLI ignores ocrd_logging.py

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#362]
Currently, in the core CLI `ocrd` (but not in the processor CLIs), none of the search paths for `ocrd_logging.py` will be used. I believe this is a regression, but I am not sure when this happened. 

As a workaround, one can use the (coarse) override `--log-level`.

**Comment by bertsky** [comment]
Not sure anymore – perhaps `ocrd` just has nothing to say (going into very strange branches).

**Comment by bertsky** [comment]
> Not sure anymore – perhaps `ocrd` just has nothing to say (going into very strange branches).

Verified. The problem is somewhere else. Sorry for the noise!

**Comment by kba** [comment]
Some hardcoded `setLogLevelOverride` somewhere perhaps?
