### ISSUE TITLE
Approximating DPI as part of image characterization

### ISSUE THREAD

**Issue by kba** [OCR-D/core#37]
If dpi/dpix/dpiy ist not in the EXIF metadata or cannot be trusted to be accurate, original page extent must be an input to the characterization.

**Comment by kba** [comment]
Very unlikely to be feasible since, if the pixel density isn't in the images, their physical extent won't be in the metadata or not reliable or not per-page etc.

**Comment by kba** [comment]
However bad the input, OcrdExif must be consistent. Output unified resolution (`sqrt(xResolution * yResolution`) and consistently set to `1` if not provided/inferrable.

**Comment by bertsky** [comment]
> Output unified resolution (`sqrt(xResolution * yResolution`) and consistently set to `1` if not provided/inferrable.

I am in the middle of fixing #256 – do you want me to fix that, too?

**Comment by kba** [comment]
I didn't realize you were working on it, I'll leave it to you then. Have a look at https://github.com/kba/ocrd-core/commit/76181e7656c50556ec37f3c402189c09c5e484cf for what I did until now.

**Comment by bertsky** [comment]
Sorry, neither did I! I tried to incorporate everything I saw in your commit in PR #257 ...

**Comment by bertsky** [comment]
All of the [revised goals](https://github.com/OCR-D/core/issues/37#issuecomment-510448988) have been captured in #257 already, therefore closing.
