### ISSUE TITLE
Disable caching in resolver

### ISSUE THREAD

**Issue by kba** [OCR-D/core#377]
With `AlternativeImage`, line images etc. the trivial caching mechanism in the resolver is getting overwhelmed leading to potential out-of-memory or out-of-open-filehandles issues.

Probably best to disable any caching and make sure files are closed properly.

**Comment by stweil** [comment]
Disabling the cache is essential for processing of a typical book with some hundred pages on a computer with a moderate RAM size (8 GB). Even on large servers it is needed to allow parallel processing of several books.

**Comment by kba** [comment]
#399
