### ISSUE TITLE
bashlib: more image mimetypes

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#380]
The following are missing in `ocrd_models.constants.EXT_TO_MIME` and `MIME_TO_EXT`:

- image/jp2
- image/pdf
- image/ps
- image/eps
- image/xps
- image/ppm
- image/pnm
- image/pbm

I know these are not meant to be processed in OCR-D. But think ocrd-im6convert etc.

**Comment by kba** [comment]
Sure, let's be complete.
