### ISSUE TITLE
bashlib: allow running without parameter file

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#381]
When parsing the CLI parameters, the ocrd-tool JSON is used to also parse the parameter file. What exactly happens when the user actually did not specify one on the command line depends on whether or not `set -u` is in effect, but it will fail – because [currently](https://github.com/OCR-D/core/blob/d20bbe52166a5889e21420ac757cd1b9b5f62f21/ocrd/ocrd/lib.bash#L114) there is no fallback. The spec of course says it is allowed to run without a parameter file, so the variable expansion here should default to an empty expression (`"${ocrd__argv[parameter]:-{}}")`).

**Comment by kba** [comment]
Alternatively or in addition, `parse_json_string_or_file` could treat an empty string as equivalent to `{}`.
