### ISSUE TITLE
messy imports?

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#394]
On current master, when I attempt `from ocrd.resolver import Resolver`, I get the following warning (stripping my absolute system paths from the output):

```
ocrd_utils/constants.py:4: UserWarning: Module ocrd was already imported from ocrd/__init__.py, but core is being added to sys.path
```

Should I be worried?

**Comment by kba** [comment]
Nah, but it is bad practice, I'll fix it.

**Comment by kba** [comment]
I cannot reproduce. I thought we had redundant imports or mis-matching `__all__` or something like that but that error is unrelated.

Have you been switching virtualenvs or updating packages? Often when running into errors like that, `find . -name '*.pyc' -delete` and/or `rm -rf **/*/__pycache__` makes these go away.

**Comment by bertsky** [comment]
> I cannot reproduce.

Neither can I. Sorry!

> Have you been switching virtualenvs or updating packages?

I must have. Good to know about the compiled cache though.
