### ISSUE TITLE
RFC: Improve command line --help further

### ISSUE THREAD

**Issue by stweil** [OCR-D/core#402]
The default help of typical OCR-D processors does not show all relevant information. Notably the `description` and the supported `parameters` are missing. Both are available in `ocrd_tool.json`, so I usually run `-J` instead of `--help` to get that information.

The core processor `ocrd` shows much better help texts, for example it always shows a description.

I suggest to enhance the help texts for other processors, too, if description / parameters are available.

**Comment by stweil** [comment]
The information `output_file_grp` could also be shown as default value for `-O, --output-file-grp TEXT      File group(s) used as output.`

**Comment by stweil** [comment]
@kba, thank you very much for the improved help. I think that is a really good step to help users with OCR-D.

I only would have expected a different ordering for the information which is given. Instead of **Parameters** / **Default Wiring** / **Options**, I suggest the order **Options** / **Parameters** / **Default Wiring**. That top down ordering fits better to **Usage** referring to **Options** which are referring to **Parameters**.

**Comment by kba** [comment]
https://github.com/OCR-D/core/pull/411

**Comment by stweil** [comment]
Again many thanks!
