### ISSUE TITLE
Warning when overwriting existing files

### ISSUE THREAD

**Issue by mjenckel** [OCR-D/core#405]
there is an open issue in our module-project about missing warnings when overwriting existing files
we could solve this for our module and add the required checks for existing files, but wouldnt it be better if the core API (which handles writing the files such as alternative images, page xml, etc) would check for existing files?
a additional `no-overwrite` option could toggle whether existing files are overwritten (with a warning) or not

**Comment by kba** [comment]
https://github.com/mjenckel/ocrd_anybaseocr/issues/25

core has checks for overwriting the METS (refusing to by default) and when downloading files (skipping downloads of existing files) but not for `workspace.add_file`. We will implement such a check but have to be careful not to be too strict and make sure this will require little changes to existing code. Basically, processors should have an `--overwrite` switch that will force overwriting and default to raise an issue before clobbering files.

If you don't want to solve it just for anybaseocr, PR are welcome!

**Comment by bertsky** [comment]
> but not for workspace.add_file

That's just not true: you have the `force` kwarg (which defaults to `False`) there since day one.

@mjenckel you probably refer to `Workspace.save_image_file` though (which delegates to `Workspace.add_file`, but inverts the default to `True`). This **does** have the same kwarg though, so it should be no problem adding `force=False` to your processor.

**Comment by kba** [comment]
Oh right, I got confusedv there with the overwrite in ocrd process. Thx for clarifying

**Comment by bertsky** [comment]
So @mjenckel can we close this, or do you want to make this issue about the default `force` of `Workspace.save_image_file`?

**Comment by mjenckel** [comment]
no, I just did not see the force option. Thanks for clarifying
