### ISSUE TITLE
run_cli should support clobber_mets

### ISSUE THREAD

**Issue by kba** [OCR-D/core#421]
@j23d reports problems when using run_cli with existing mets files:

```
>   File 
> "/home/j23d/projects/ocrd/ocrd_all/venv/lib/python3.6/site-packages/ocrd/resolver.py", 
> line 154, in workspace_from_url
>     self.download_to_directory(dst_dir, mets_url, 
> basename=mets_basename, if_exists='overwrite' if clobber_mets else 
> 'raise')
>   File 
> "/home/j23d/projects/ocrd/ocrd_all/venv/lib/python3.6/site-packages/ocrd/resolver.py", 
> line 87, in download_to_directory
>     raise FileExistsError("File already exists and if_exists == 
> 'raise': %s" % (dst_path))
> FileExistsError: File already exists and if_exists == 'raise': 
> /tmp/ocrd_butler_results/PPN80041750X-78b5d16e-3c3c-11ea-aa09-901b0e128c3f/PPN80041750X.mets.xml
```

**Comment by j23d** [comment]
run_cli works without a problem if https://github.com/OCR-D/core/blob/034d5388cc735169c0c0b173c8539d08c08c7afd/ocrd/ocrd/resolver.py#L154

is changed to

`self.download_to_directory(dst_dir, mets_url, basename=mets_basename, if_exists='overwrite' if clobber_mets else 'skip')`

But I don't know other possible implications of the change.

**Comment by kba** [comment]
> But I don't know other possible implications of the change.

That's actually a reasonable solution because we do not want to overwrite the existing METS and skipping over the download makes sense in this case.
