### ISSUE TITLE
Allow overwriting output groups

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/core#434]
@bertsky wrote in #245:
>  (The --force option is not exposed to those CLIs.)

I often have a usage pattern of 1. force-removing an output group to 2. run a processor again, e.g.:

~~~
ocrd workspace remove-group -rf OCR-D-IMG-BINPAGE
ocrd workspace remove-group -rf OCR-D-IMG-BIN
ocrd-olena-binarize -I OCR-D-IMG -O OCR-D-IMG-BINPAGE,OCR-D-IMG-BIN \
    -p "$ocrd_olena_binarize_parameters"
~~~
or
~~~
ocrd workspace remove-group -rf OCR-D-SEG-LINE
ocrd-sbb-textline-detector -I OCR-D-IMG-BINPAGE -O OCR-D-SEG-LINE \
    -p "$ocrd_sbb_textline_detector_parameters"
~~~

It would be great if the processor CLI wrapper would provide `--force` to reduce this to:

~~~
ocrd-olena-binarize --force -I OCR-D-IMG -O OCR-D-IMG-BINPAGE,OCR-D-IMG-BIN \
    -p "$ocrd_olena_binarize_parameters"
~~~
and
~~~
ocrd-sbb-textline-detector --force -I OCR-D-IMG-BINPAGE -O OCR-D-SEG-LINE \
    -p "$ocrd_sbb_textline_detector_parameters"
~~~

**Comment by bertsky** [comment]
Yes, this would be the simplest solution I think. @kba, this would only change the default `force` for `ocrd_mets.add_file`, but could thus be easily wrapped by workflow engines.

**Comment by kba** [comment]
> @kba, this would only change the default force for ocrd_mets.add_file, but could thus be easily wrapped by workflow engines.

That would be easy but it's not the same as removing the whole file group before running the processors. I'd prefer removing the whole group because that makes it clearer which files were created with `--force`. But maybe I'm missing a use case here?

And probably not call it `--force` but `--overwrite` because the latter is more specific.

**Comment by bertsky** [comment]
> That would be easy but it's not the same as removing the whole file group before running the processors. I'd prefer removing the whole group because that makes it clearer which files were created with `--force`.

You're absolutely right. This could introduce inconsistencies, the least of which would be having two pages with the same `pageId` in the same fileGrp.

> But maybe I'm missing a use case here?

Maybe. But the above use-case it the most pressing, and it does warrant removing the whole output filegrp.

But perhaps we should take special action in the case where the processor was only requested for a single page. (Like raising an exception or only removing that particular pageId.)

> And probably not call it `--force` but `--overwrite` because the latter is more specific.

Agreed, again.

**Comment by mikegerber** [comment]
> And probably not call it `--force` but `--overwrite` because the latter is more specific.
Just ideas for the semantics:

- `--overwrite` would overwrite the whole group if it exists
   (that is remove *all* pages, regardless of what pages the processor will process)
- `--overwrite --page-id xyz` would overwrite just the page if it exists

The first one is my use case, the latter might be useful for someone.

**Comment by bertsky** [comment]
> Just ideas for the semantics:
> 
>     * `--overwrite` would overwrite the whole group if it exists
>       (that is remove _all_ files in the group for all pages, regardless of what pages the processor will process)
> 
>     * `--overwrite --page-id xyz` would overwrite just the files for the specified page if they exist
> 
> 
> The first one is my use case, the latter might be useful for someone.

Yes, this even naturally resolves the ambiguity of the case when the input file group does not cover/contain all pages already existing in the output file group to be overwritten.

**Comment by mikegerber** [comment]
(We could also discuss a "quasi atomic" approach of first writing to a temporary output group, and if that worked without errors, replacing the output group with the new one. I'm not sure if that would be a different issue, though.)

**Comment by kba** [comment]
>     --overwrite would overwrite the whole group if it exists
    (that is remove all files in the group for all pages, regardless of what pages the processor will process)
>    --overwrite --page-id xyz would overwrite just the files for the specified page if they exist

Sounds good, I'll go implement it this way. 

> first writing to a temporary output group, and if that worked without errors, replacing the output group with the new one

That would also be possible but could cause different problems with consistency and produce counterintuitive results ("I pressed Ctrl-C after 30 images but processor produced no results in the `output-file-grp`").

**Comment by mikegerber** [comment]
> > first writing to a temporary output group, and if that worked without errors, replacing the output group with the new one
> That would also be possible but could cause different problems with consistency and produce counterintuitive results ("I pressed Ctrl-C after 30 images but processor produced no results in the `output-file-grp`").

We should open another issue to discuss this if this ever comes up again.

**Comment by bertsky** [comment]
@kba just a reminder that there is still the difficulty of "processor side effects": the new output, as well as the old output, could contain (`AlternativeImage`) references to images in other file groups.

**Comment by kba** [comment]
@mike-gerber Can you please have a look at https://github.com/OCR-D/core/pull/471? PR is ready and I want to release it ASAP. Thanks!

**Comment by mikegerber** [comment]
Thanks for implementing this, this makes working with the CLI so much easier for me :1st_place_medal:
