### ISSUE TITLE
workspace.add_file without incremental refcounts

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#446]
I don't know if this is intentional: When looping over large workspaces and adding files to them, the `workspace.mets._file_by_id` dict keeps growing and thus leaks all the new `OcrdFile` and METS file element etree references. This can create extreme memory overhead and slow down eventually (because each new file has to be compared to ever more existing IDs).

Perhaps one can at least try to sever the references to the file etrees?

But an opt-out to the general `_file_by_id` dict mechanism is probably best seen as part of #416, right?

**Comment by kba** [comment]
I don't think we need the `_file_by_id` mechanism at all anymore. That was mostly to accomodate OcrdFile having unserialized information such as the filename of a local filename of a remote file. We've moved away from that pattern. I don't see the connection to #416 other than that we should fix both issues soon to support mass digitisation.

**Comment by bertsky** [comment]
> I don't think we need the `_file_by_id` mechanism at all anymore.

Ok, that's good news!

**Comment by bertsky** [comment]
Related: With very large workspaces, the current implementation of `OcrdMets.find_files` is quite inefficient. It first makes a global XPath query to get all file IDs, then another to find each file ID again in the tree.

IMHO this should be implemented as a single loop with `iterfind()` or `findall()`. pageId filtering and local_filename filtering can then be done in the loop body I think.

**Comment by kba** [comment]
I noticed that as well when removing the trivial caching. On my TODO list.

**Comment by bertsky** [comment]
BTW This is a common cause of inefficiency. Not just when growing workspaces by adding more and more files. Any processor on a large workspace has to pay the penalty before it can start.
