### ISSUE TITLE
Cache: Changes in METS do not trigger reload.

### ISSUE THREAD

**Issue by wrznr** [OCR-D/core#45]
If the METS file changes (cf. https://github.com/kba/ocrd-assets/pull/1), it should be “reloaded” into the cache.

**Comment by kba** [comment]
The cache has no validation/eviction mechanism at the moment, main concern was to avoid any subsequent HTTP requests to save bandwidth. An implementation should request HTTP and handle `200/404/304/ETag/Last-Modified` and not cache empty responses.

Currently, I just empty the cache with `rm -rf /tmp/cache-pyocrd` when I want to reload.

Note: You can disable caching by passing `cache_enabled=False` to the Resolver.

**Comment by kba** [comment]
You can now also disable the cache in the CLI with `--no-cache`, #100.
