### ISSUE TITLE
[Request] Track execution time for each processed module

### ISSUE THREAD

**Issue by M3ssman** [OCR-D/core#461]
For profiling purposes, it is important to track execution time for an ocr-d workflow step to identify potential performance bottlenecks.

Please provide a configurable functionality that can be utilized this way.

**Comment by kba** [comment]
You mean in `ocrd process`? That can be implemented easily - is that what you want?

**Comment by M3ssman** [comment]
What do you mean with `ocrd process` ? Stuff from `ocrd.processor.base`-package? 

I'd like to be able to set a specific flag (`--profile` or alike) for each module project that forms a stage of an OCR-D-Pipeline, to enable time measurement of the project module execution time. When finished, the duration should be printed out or logged. Unfortunately I can't specify which OCR-D component is the best place to provide something like this, but I guess the main module project API, since it should be includedable for every step.

So, if I afterwards do explorations/ need statistics I could gather the information from the log/stdout.

**Comment by bertsky** [comment]
> What do you mean with `ocrd process` ?

The CLI (cf `ocrd process --help`).

In a way, this is already present there (it adds a `Start processing task` and `Finished processing task` log message around each processor call, which you could then distill into statistics).

> So, if I afterwards do explorations/ need statistics I could gather the information from the log/stdout.

You could do that already (even without using `ocrd process`) from the existing log messages. But not every processor may be noisy enough. And of course, parsing log message dates for duration statistics is cumbersome.

I guess what core could provide here is a dedicated _logger_ (which can then be configured with a separate file handler and time formatting), and send a message to that whenever `Processor.process()` enters and exits. The place to do that is [here](https://github.com/OCR-D/core/blob/e0ee7a12c0c52a14eb04b8add9b673314cbcc109/ocrd/ocrd/processor/base.py#L57) – this gets called by `ocrd_cli_wrap_processor` and thus any current CLI.

**Comment by kba** [comment]
You mean using a dedicated logging context name, like `performance` or `profile` and set up logging to output that particular log stream to a different file (which will be simpler once the logging-config PR lands)?

```python
# in run_processor
profileLogger = getLogger('performance')
t0 = time.time()
processor.process()
t1 = time.time() - t0
profileLogger('%f ms for %s" % (t1 * 1000, ocrd_tool['executable'])
```

**Comment by M3ssman** [comment]
@kba Yes! Something alike! And let's stick to seconds as unit!
