### ISSUE TITLE
core logger has the wrong format since 2.5.0

### ISSUE THREAD

**Issue by kba** [OCR-D/core#466]
In 6d0eb56 I added the date part to log statement's output and now the [log message format in core [is not spec-compliant](https://ocr-d.de/en/spec/cli#logging) anymore.

**Comment by M3ssman** [comment]
@kba I wonder why there's no date part in the log-specs integrated. It's a very common log pattern this. There must have been a good reason to skip this. Could you please explain?

**Comment by kba** [comment]
To keep the logs succinct, mostly. Logging the date makes sense for processes that run indefinitely like web servers but for a process like OCR-D, we thought it was just 11 characters that are the same on every line, shifting the interesting parts of the log to the right.

**Comment by bertsky** [comment]
But would that argument not equally count for the time substring? Especially now that we have a dedicated CPU time logger.

Removing the time substring would also make the log messages directly diffable (for debugging and comparison).

**Comment by bertsky** [comment]
Conversely, IMO date and time is not only relevant for processes that run indefinitely. If I process a large amount of data and later-on find in the (usually huge) log some problem I want to investigate, then the date and time can help me find the relevant files on the disk via their time stamp. (Remember, the log messages themselves are not required to give enough identifying context each time, like which workspace / page / region / line the error happened in.)

**Comment by kba** [comment]
Three options:

1. keep the current format (merge this PR)
2. change spec to include date (close this PR)
3. remove timestamp altogether

I prefer 1. because it is short and still useful for debugging. If you really need the information on what day a process ran, my first idea would be a sensible log file naming format. You could use the `ts(1)` tool from moreutils to prepend timestamps to logged stmts:

```sh
seq 10 |ts '%Y-%d-%m '
```

By that same reasoning though, we could also implement 3 and make timestamps responsibility of the user.

A fourth possiblity would be to [log just time deltas from log message to log message](https://stackoverflow.com/questions/31521859/python-logging-module-time-since-last-log) (which is what I personally use the logs for mostly: debugging and profiling).

@VolkerHartmann @wrznr @cneud any opinions?

**Comment by kba** [comment]
The agreement was to keep the current format. But of course you're free to use the `tl(1)` solution or to configure the logging to you liking using [a configuration file](https://github.com/OCR-D/core/pull/460)
