### ISSUE TITLE
Add dummy processor

### ISSUE THREAD

**Issue by VolkerHartmann** [OCR-D/core#468]
Sometimes it is useful not to run certain processors. In this case it would be helpful to simply replace it with a dummy without touching the other parameters.
In case of multiple output groups only first output group will be created with the original PAGE.XML files.

**Comment by bertsky** [comment]
Sounds like something #385 can provide (by specifying a no-op like `cp` as command).

**Comment by bertsky** [comment]
> Sounds like something #385 can provide (by specifying a no-op like `cp` as command).

But you would already get that from `ocrd-cis-ocropy-binarize` with `method=none`.

However, both do add an `AlternativeImage` with `comments=binarized` – which is not what you want IIUC. You only want a copy (verbatim or parse-and-regenerate) of the PAGE-XML, keeping the same references to derived images, right?

Incidentally, I think such a no-op processor could also be useful for automated tests.

**Comment by kba** [comment]
In the `test_processor.py` test suite we use this as a dummy processor:

```python
DUMMY_TOOL = {
    'executable': 'ocrd-test',
    'steps': ['recognition/post-correction'],
    'parameters': {
        'baz': {
            'type': 'string',
            'default': 'bla'
        }
    }
}

class DummyProcessor(Processor):

    def process(self):
        pass

    def __init__(self, *args, **kwargs):
        kwargs['ocrd_tool'] = DUMMY_TOOL
        kwargs['version'] = '0.0.1'
        super(DummyProcessor, self).__init__(*args, **kwargs)
```

For the task sequence tests, we even install them as scripts into a modified `$PATH`. @VolkerHartmann is that what you have in mind for a dummy processor? Or should it be a little bit smarter and output something on process?

**Comment by kba** [comment]
@VolkerHartmann Can you comment whether the proposed "real dumb" dummy processor fits your use case?

**Comment by VolkerHartmann** [comment]
Sorry, I forgot to answer. 
What do you mean with 'output something on process'?
Use case I want to skip second binarization:
ocrd-anybaseocr-crop -I OCR-D-IMG-BIN -O OCR-D-IMG-BIN-CROP
ocrd_dummy -I OCR-D-IMG-BIN-CROP -O OCR-D-IMG-BIN-CROP-BIN
ocrd-cis-ocropy-denoise -I OCR-D-IMG-BIN-CROP-BIN -O OCR-D-IMG-BIN-CROP-BIN-DENOISE

The dummy processor should create the output group, copy the PAGE-XML files in this group and add them to the mets file.

It's like the processor Robert mentioned without adding an alternative image.
