### ISSUE TITLE
serialise OrderedGroup(Indexed) correctly sorted by index 

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#475]
Our current generateDS model does not put an `OrderedGroupType` or `OrderedGroupIndexedType`'s elements (i.e. the contained sequence of `RegionRefIndexedType`, `OrderedGroupIndexedType` or `UnorderedGroupIndexedType`) in their correct **sort order**: PAGE-XML semantics and PRImA libraries/tools require a strict `@index` ordering.

Cf https://github.com/PRImA-Research-Lab/prima-page-viewer/issues/15#issuecomment-623492135

Probably related to #240

**Comment by kba** [comment]
> Not sure if an actual requirement, but it does not hurt to also order TextEquiv by their @index.

Yep, the solution would be similar and the additional CPU cycles do not hurt.

**Comment by kba** [comment]
implemented in #478
