### ISSUE TITLE
performance of `page-id` on large workspaces

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#482]
I am afraid my conjecture in [#448](https://github.com/OCR-D/core/pull/448#pullrequestreview-393997881) that we could become slower than before has now proven correct. I have a workspace here with more than 8000 pages (of a training corpus) times 18 fileGrps, and it became **unacceptably slow**. (I can provide the METS on request.)

Here is a little statistics:

| | **v2.6.0** | **#481 and #484** |
|---|---|---|
| `time ocrd workspace find -k url` | 7sec | 6sec |
| `time ocrd workspace find -k pageId` | 193min | 4min |
| `time ocrd workspace find -g page0001 -k url` | 261min | 2sec |

(The same holds for processors, so it's not only the `ocrd` CLI.)

Looking at [lxml's performance recommendations](https://lxml.de/performance.html), I find the following advice relevant:
> ## Tree traversal
> Another important area in XML processing is iteration for tree traversal. If your algorithms can benefit from step-by-step traversal of the XML tree and especially if few elements are of interest or the target element tag name is known, the .iter() method is a good choice
> ...
> In general, lxml is very fast for iteration, but loses ground against cET when many Elements are found and need to be instantiated. So, the more selective your search is, the faster lxml will run.
> ## XPath
> ...
> lxml provides more than one way of accessing it and you should take care which part of the lxml API you use. The most straight forward way is to call the xpath() method on an Element or ElementTree
> This is well suited for testing and when the XPath expressions are as diverse as the trees they are called on. However, if you have a single XPath expression that you want to apply to a larger number of different elements, the XPath class is the most efficient way to do it
> Note that this still allows you to use variables in the expression, so you can parse it once and then adapt it through variables at call time. In other cases, where you have a fixed Element or ElementTree and want to run different expressions on it, you should consider the XPathEvaluator
> ...
> Note that tree iteration can be substantially faster than XPath if your code short-circuits after the first couple of elements were found. The XPath engine will always return the complete result set, regardless of how much of it will actually be used.
> Here is an example where only the first matching element is being searched, a case for which XPath has syntax support as well

So I believe we should replace the large `.xpath('//mets:file')` with an `.iter(tag='mets:file')`, and at least factor the smaller `.xpath()` for `pageId` out of the loop body.

The latter I already did in #481, with stunning effect (see above).

For the `-k pageId` which fires `ocrd_mets.OcrdMets.get_physical_page_for_file()` I still don't know how to do better. Maybe when we know for `find_files` that we are also interested in pageIds, we could add a second main loop over `/mets:mets/mets:structMap[@TYPE="PHYSICAL"]/mets:div[@TYPE="physSequence"]/mets:div[@TYPE="page"]` mapping their `./mets:fptr/@FILEID` to their `./@ID`?

**EDIT** did the latter in #484 and updated the timings.

@kba I would consider this fixed, unless you want to follow through with `iter()`.

**Comment by kba** [comment]
Thanks for evaluating this and sorry to hear performance is so dismal for large datasets. I was quietly hoping to avoid it but as the numbers show, we need to optimize the search loop or even replace the current loop altogether for specific circumstances. I will merge #481 right away and will investigate this further tomorrow.

Can you share with me the dataset you use to evaluate? None of the samples I have at my disposal are large enough and I don't want to create something that might not be realistic.

**Comment by bertsky** [comment]
[mets.zip](https://github.com/OCR-D/core/files/4629946/mets.zip)

**Comment by bertsky** [comment]
It's also obviously a question of what queries are done. The `-k pageId`, which is AFAIK the only pathological case remaining, is realistic though: it's needed for loops like that in `ocrd-olena-binarize` or `ocrd-im6convert`.
