### ISSUE TITLE
image API: respect order of derived image features

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#524]
The functions `Workspace.image_from_page` and `image_from_segment` must crop according to `Page/Border/Coords` or `TextRegion/Coords`, and they must rotate according to `Page/@orientation` or `TextRegion/@orientation`.

But what if the segment has both?

1. crop-first: 
   - find the bbox of the border polygon, mask the parts outside of the polygon with background, and crop to that bbox
   - then rotate the cropped image, which increases the image size
2. rotate-first:
   - rotate, which increases the image size
   - find the bbox of the (rotated) border polygon in the rotated image, mask the parts outside of the polygon with background, and crop to that bbox

These 2 approaches create different images and different coordinates. So whatever gets used, must be used consistently. 

Now core is always responsible for the coordinate transformations, but not always responsible for producing derived images (as processors can create and annotate AlternativeImage themselves, which will have priority over core-generated ones if they meet all requested features). Thus, it has to _know_ which ordering of both operations has been applied when some `AlternativeImage` has both.

The only choice we have IMHO is making `AlternativeImage/@comments` order-sensitive. That is, `'binarized,cropped,deskewed'` is 1 and `'binarized,deskewed,cropped'` is 2.

When there is no AlternativeImage yet, the decision is up to core.

For the [implementation](https://github.com/OCR-D/core/blob/f708420d806ab6363917e3a53519d85505327568/ocrd/ocrd/workspace.py#L366-L535), this unfortunately means a large restructuring of both functions.

Or am I missing something?

**Comment by kba** [comment]
I understand the general problem and that we'll have to adapt `image_from*` to accomodate different order of cropping+rotation. I am not sure what the default behavior should be. Is one superior to the other? Solution 1 (crop, then rotate) seems simpler. And we should add that decision to the specs (maybe combining definition with the [preprocessing extensions you proposed](https://github.com/OCR-D/spec/issues/159). I've added it to the agenda for our [call tomorrow](https://hackmd.io/OOMgg3ZeSqK4vfKL1wRbwQ?edit) so we can agree on a way forward for a default and then adapt the `image_from_*` methods.

**Comment by bertsky** [comment]
To elaborate: core currently only implements 1, and this is fine as long as there is no workflow with deskewing before cropping. This can only happen on the page level, but since ocrd-anybaseocr-crop recommends deskewing first (because it can only handle rectangular margins), and the workflow guide of course follows that, it's still a frequent case.

**Comment by bertsky** [comment]
> I am not sure what the default behavior should be. Is one superior to the other? Solution 1 (crop, then rotate) seems simpler.

Yes it is, and for the levels below page, it's the only one.

> And we should add that decision to the specs

the problem is that this section is hopelessly underspecified. We should have cast [the solution from core into spec](https://github.com/OCR-D/spec/issues/116) long ago...
