### ISSUE TITLE
Regression in ocrd process

### ISSUE THREAD

**Issue by kba** [OCR-D/core#529]
With 2.8.0, these are functionally equivalent:

```sh
ocrd-olena-binarize -I MAX -O OCR-D-BIN -p '{"impl": "sauvola"}'
ocrd process -l DEBUG 'olena-binarize -I MAX -O OCR-D-BIN -p "{\"impl\": \"sauvola\"}"
```

With 2.10.4, the `ocrd process` call never calls ocrd-olena-binarize.

**Comment by bertsky** [comment]
Solution described [here](https://github.com/OCR-D/core/issues/540#issuecomment-659426787)
