### ISSUE TITLE
What to do if --mets is unspecified and no mets.xml is present

### ISSUE THREAD

**Issue by kba** [OCR-D/core#562]
Currently, a processor call, if `--mets` was not given and no `mets.xml` is present in $PWD, the `--help` message is given. The reasoning is that if a user calls a processor without any arguments, it makes more sense to provide general help instead of the very specific error message `mets.xml could not be found`.

However from feedback from @dla-kramski, @ElexaDigitalia_twitter and others, this behavior (in core since 2.12.0 https://github.com/OCR-D/core/issues/438 https://github.com/OCR-D/spec/pull/156) is confusing because it is also triggered if `-I` and `-O` are provided.

So I propose to change the behavior to this:

* If no options/arguments *at all* are provided to a processor, then print the `--help`
* If METS cannot be found, raise an error saying so

**Comment by bertsky** [comment]
> So I propose to change the behavior to this:
> 
>     * If no options/arguments _at all_ are provided to a processor, then print the `--help`
> 
>     * If METS cannot be found, raise an error saying so

Looks good. (But for things that might go wrong in scripts/makefiles, I'd also make the first case exit with non-zero besides showing the help text.)
