### ISSUE TITLE
Resolver.workspace_from_url: usage of clobber_mets not consistent with the docstring

### ISSUE THREAD

**Issue by hnesk** [OCR-D/core#563]
clobber_mets = False does not raise an exception for existing mets.xml ('raise'), but fails silently ('skip')
https://github.com/OCR-D/core/blob/4e11b8e70a2426f3d25466f462db13bf31215919/ocrd/ocrd/resolver.py#L114
see:
https://github.com/OCR-D/core/blob/4e11b8e70a2426f3d25466f462db13bf31215919/ocrd/ocrd/resolver.py#L154

I don't know what would be the right thing to do: Fix the docstring or fix the implementation?

**Comment by bertsky** [comment]
> I don't know what would be the right thing to do: Fix the docstring or fix the implementation?

I'd prefer the latter option.

**Comment by hnesk** [comment]
Oh, I just found this PR https://github.com/OCR-D/core/pull/425#pullrequestreview-346994175

**Comment by bertsky** [comment]
@kba this needs to be revisited – including the discussion after #425.

We still have:
https://github.com/OCR-D/core/blob/987da9bb59cf8ddb5bc9f706d01db7652d092178/src/ocrd/resolver.py#L221

At the very least, the docstring needs to be fixed.
