### ISSUE TITLE
Processors: support iterating over multiple input_file_grp

### ISSUE THREAD

**Issue by kba** [OCR-D/core#568]
>> @bertsky in https://github.com/OCR-D/ocrd_segment/pull/41#discussion_r474651827
> Yes, [`ocrd_segment.import_image_segmentation.zip_input_files`] in combination with a loop over these file tuples instead of Processor.input_files. I have first seen that recipe in @finkf's ocrd-cis-align, then re-used it for ocrd-cor-asv-ann-evaluate and others. Would be great if this entered core (including error messages when some pages don't have files for all input fileGrps etc)...

**Comment by bertsky** [comment]
Fixed by #635
