### ISSUE TITLE
bashlib: better tooling required to handle PAGE/images in same fileGrp

### ISSUE THREAD

**Issue by kba** [OCR-D/core#571]
c.f. https://github.com/OCR-D/ocrd_olena/pull/68/files this should be easier.

**Comment by bertsky** [comment]
Or expose `Processor.input_files` directly to bashlib.

**Comment by kba** [comment]
Since we now have `ocrd bashlib input-files` is this solved?

**Comment by bertsky** [comment]
Yes (just forgot to link).
