### ISSUE TITLE
repo/spec not updated by make

### ISSUE THREAD

**Issue by stweil** [OCR-D/core#593]
`repo/spec` is cloned when running `make all` with `ocrd_all`, but never updated in later builds. Those builds then overwrite `ocrd_validators/ocrd_validators/ocrd_tool.schema.yml` by an older version.

**Comment by stweil** [comment]
Maybe using submodules would be better than cloning `HEAD` for `spec`, `assets` and `gh-pages`?

**Comment by bertsky** [comment]
Yes, that's exactly what I proposed in #337 – but was turned down quickly.

**Comment by stweil** [comment]
`repo/spec` could also be updated in `ocrd_all/Makefile` of course. So there are a lot of choices. We just have to select one.

I don't know whether an outdated `repo/spec` can cause malfunctions of OCR-D. It definitely causes changes in the file tree which are reported by `git status` for `ocrd_all`. Ideally there should not be such changes (currently `ocrd_anybaseocr` is another candidate with modified and untracked content).

**Comment by kba** [comment]
> Yes, that's exactly what I proposed in #337 – but was turned down quickly.

Since we've embraced submodules in most other projects since then, we should do the same for spec and assets in core.

**Comment by kba** [comment]
fixed by https://github.com/OCR-D/core/pull/596
