### ISSUE TITLE
Prevent serializing empty reading order

### ISSUE THREAD

**Issue by kba** [OCR-D/core#602]
An empty/self-closing `pc:ReadingOrder` is not valid against the PAGE XSD schema and leads to errors when using pagelib, e.g. with the PageConverter in ocrd_fileformat (c.f. https://github.com/OCR-D/ocrd_tesserocr/issues/153).

**Comment by bertsky** [comment]
Rationale: Processors doing segmentation will often create `ReadingOrder` unconditionally to be filled in with results. If however for some page no valid segments can be detected/added, then one would require an extra step to remove `ReadingOrder` again.
