### ISSUE TITLE
`ocrd workspace remove-group` fails to remove existing group

### ISSUE THREAD

**Issue by stweil** [OCR-D/core#617]
[This METS file](https://digi.bib.uni-mannheim.de/fileadmin/digi/477429599/477429599.xml) contains a `FULLTEXT` file group made for ABBYY. It must be removed before adding a new file group with OCR-D results. This does not work with `ocrd remove-group`:

    ocrd workspace -m 477429599.xml remove-group --recursive FULLTEXT
    [...]
    Exception: File not locally available <OcrdFile fileGrp=TEMP, ID=FILE_0001_ALTO, mimetype=text/xml, url=https://digi.bib.uni-mannheim.de/fileadmin/digi/477429599/alto/477429599_0001.xml, local_filename=---]/>

**Comment by kba** [comment]
Try `remove-group --recursive --force FULLTEXT`

>   `-f, --force`      Continue removing even if group or containing files not found in METS

**Comment by stweil** [comment]
I did that of course. It works neither, but throws a different error.

**Comment by stweil** [comment]
Pull request #618 fixes the `AttributeError` with `--force`.

**Comment by stweil** [comment]
PR #618 was merged, so this is fixed now, thank you.
