### ISSUE TITLE
bulk-add: improve usability

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#641]
IMHO `ocrd workspace bulk-add` can be made more user-friendly:

1. Do _not_ convert the `FILE_GLOB` argument (which could be an actual glob, or a shell-expanded list of files) from relative path names to absolute. With absolute path names there is always the need to remove the right prefix within `--regex`. But with relative path names the regex could just start with it, which is more intuitive and less error-prone (as no directory prefix needs to be matched).
1. Do _not_ make the `--url` option required. For the special case when the `add_file` should not copy files into the workspace physically, but only add them to the METS wherever they are, this would save time and avoid errors (because when the URL does not match exactly, files will be copied, which might be surprising and leave a mess in the directory).
1. Do _not_ require a `--file-id` argument. Often it is good enough to just generate some unique ID automatically.
1. Fix the docstring such that newlines don't get removed. It is currently printed as:
```
 \b Example:     ocrd workspace bulk-add \\             --regex
  '^.*/(?P<fileGrp>[^/]+)/page_(?P<pageid>.*)\.(?P<ext>[^\.]*)$' \\
  --file-id 'FILE_{{ fileGrp }}_{{ pageid }}' \\             --page-id
  'PHYS_{{ pageid }}' \\             --file-grp "{{ fileGrp }}" \\
  --url '{{ fileGrp }}/FILE_{{ pageid }}.{{ ext }}' \\
  path/to/files/*/*.*
```

So all in all, this example could be simplified to:
```
 Example:
   ocrd workspace bulk-add \\
      --regex '^(?P<fileGrp>[^/]+)/page_(?P<pageid>.*)\.(?P<ext>[^\.]*)$' \\
      --page-id 'PHYS_{{ pageid }}' \\
      --file-grp "{{ fileGrp }}" \\
   OCR-D-IMG/page_*.*
```

**Comment by kba** [comment]
Agree on all your proposed changes.

**Comment by bertsky** [comment]
Also, there should be some sensible error message for non-matches. Currently, there is no telling what happened:
```
  File "/home/scott/src/github/OCR-D/ocrd_all/venv/lib/python3.6/site-packages/ocrd/cli/workspace.py", line 300, in workspace_cli_bulk_add
    file_dict[param_name] = file_dict[param_name].replace('{{ %s }}' % group_name, group_dict[group_name])
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by bertsky** [comment]
(Background: I would like to reimplement ocrd-import, which is painfully slow, based on parallel conversion and bulk-add.)
