### ISSUE TITLE
TensorFlow 2.4 requires Numpy 1.19

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/core#642]
~~~
tensorflow 2.4.0rc1 requires numpy~=1.19.2, but you'll have numpy 1.18.5 which is incompatible.
~~~

However ocrd_utils requires numpy < 1.19.

**Comment by kba** [comment]
tf 2.4 requires numpy `=~1.19.2` but tf < 2.4 requires numpy `< 1.19` according to @stweil in ac86b8ec. How can we reconcile these conflicting requirements?

**Comment by bertsky** [comment]
> Why does ocrd_utils specify this requirement? Is it the right place?

> How can we reconcile these conflicting requirements?

I think we could start not trying to solve this in ocrd_utils, but in the modules requiring TF and their ocrd_all rules.

I'm not sure whether TF at least correctly (w.r.t. numpy) install itself via pip. If it does, then as long as there are no conflicting numpy requirements from other packages in that module (or rather, sub-venv), we probably don't need to do anything at all.

**Comment by kba** [comment]
OK, I will try to remove the numpy requirement and see what that breaks.

**Comment by bertsky** [comment]
> OK, I will try to remove the numpy requirement and see what that breaks.

ocrd_utils itself does need numpy, but I doubt we need some specific version (and could not find discussion of that anywhere).

**Comment by kba** [comment]
Sorry, I meant "numpy version requirement". AFAIK we don't have any specific version requirements for core itself.

**Comment by mikegerber** [comment]
> > Why does ocrd_utils specify this requirement? Is it the right place?
> I think we could start not trying to solve this in ocrd_utils, but in the modules requiring TF and their ocrd_all rules.

(I had deleted that comment because it sounded harsh on second thought.) I also think ocrd_utils should not solve this.

**Comment by mikegerber** [comment]
numpy does installs correctly using pip's `--use-feature=2020-resolver"`, but I would need to check again when ocrd_utils removes the conflict

**Comment by b2m** [comment]
@kba on Gitter:
> We upgrade pip as the first step in make all in ocrd_all and I haven't had a runtime VersionConflict in a long time.
> I am currently investigating this in the context of OCR-D/core#642, so if you notice any such problems,
> esp. at runtime, please let me know, so we can track down the problem.

To reproduce the mentioned `VersionConflict` use the setup described in https://gist.github.com/b2m/d29c9e5dba9658bb3e5aad6d6d93c3bb and remove the `--use-feature=2020-resolver` part in ` pip3 install browse-ocrd --use-feature=2020-resolver`.

Running the container then results in:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/browse-ocrd", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/ocrd_browser/main.py", line 42, in main
    app = OcrdBrowserApplication()
  File "/usr/local/lib/python3.7/site-packages/ocrd_browser/application.py", line 16, in __init__
    self.view_registry = ViewRegistry.create_from_entry_points()
  File "/usr/local/lib/python3.7/site-packages/ocrd_browser/view/registry.py", line 17, in create_from_entry_points
    view_class = entry_point.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.19.3 (/usr/local/lib/python3.7/site-packages), Requirement.parse('numpy<1.19.0,>=1.17.0'), {'ocrd-utils'})
```

**Comment by kba** [comment]
2.21.0 removed the restriction and I haven't encountered numpy VersionConflicts so far.
