### ISSUE TITLE
ocrd workspace find --download does not use correct workspace prefix

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#644]
There is a flaw in the workspace directory resolution of the CLI:

    ocrd workspace -d Brsfded_39946221X-18920413 find -G ORIGINAL --download

This will:

- change remote links in `Brsfded_39946221X-18920413/mets.xml` to local ones, now pointing to `ORIGINAL/*`
- download the files under `Brsfded_39946221X-18920413/Brsfded_39946221X-18920413/ORIGINAL` (one level too deep)

**Comment by bertsky** [comment]
Also true for `prune-files` BTW (i.e. the place where this will _look_ for local files is wrong, so it will simply delete all file entries). Therefore, not sure if this is related to #643

**Comment by kba** [comment]
Can reproduce the find/download issue. Until I found the problem, a workaround is to chdir into the workspace and omitt the `-d` option.

**Comment by bertsky** [comment]
Thanks!
