### ISSUE TITLE
ocrd workspace rename-group

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/core#646]
I'd like an `ocrd workspace rename-group` operation, because:

1. It would be a useful generic operation to manipulate workspaces
2. I'd like to run some other processors to a temporary file group and rename the group after completion. (That would make long running processing a bit more robust because I would know that TEMP.450894 is probably unfinished while a properly named group is probably finished. Not perfect because it can't be done atomic, I think, but it would help.)

**Comment by kba** [comment]
@mikegerber please have a look at https://github.com/OCR-D/core/pull/655

**Comment by mikegerber** [comment]
As #655 is merged, I think this can be closed!
