### ISSUE TITLE
ocrd workspace add: Autodetect MIME type

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/core#657]
Could `ocrd workspace add` autodetect JPEG/PAGE/TIFF/PNG MIME types? This would increase usability a bit.

**Comment by mikegerber** [comment]
*Especially* would that be useful for `application/vnd.prima.page+xml`

**Comment by kba** [comment]
> _Especially_ would that be useful for `application/vnd.prima.page+xml`

We have mappings from extension to mimetype and vice versa and we guess mimetype from extension already in `ocrd workspace bulk-add` so I see no reason why we should not do so in `ocrd workspace add` as well.

`.xml` would need to be mapped to `application/vnd.prima.page+xml`, so for other XML formats like ALTO or TEI, `--mimetype` would still need to be set explicitly

**Comment by mikegerber** [comment]
I think that should be fine, as I am mainly interested in improving the default (adding images (and maybe PAGE) with valid page IDs and produce a working workspace).
