### ISSUE TITLE
Drop dependency on exiftool

### ISSUE THREAD

**Issue by kba** [OCR-D/core#71]
For the use cases we have a solution like https://github.com/ianare/exif-py or https://github.com/hMatoba/Piexif would be preferrable so users (and tools depending on OCR-D/core as a lib) do not have to install `libimage-exiftool-perl`.

**Comment by kba** [comment]
No, it's actually extracting, just isnt' visible in the `hachoir-metadata` output but can be accessed programmatically.

**Comment by cneud** [comment]
While one certainly can't beat `exiftool` - for our use cases, might it not be sufficient to use [Pillow](https://github.com/python-pillow/Pillow), which has e.g. [ExifTags.py](https://github.com/python-pillow/Pillow/blob/master/src/PIL/ExifTags.py) and can read TIF/JPG/PNG/JP2?

**Comment by kba** [comment]
Thanks for the tip will investigate tomorrow, I want this and the libxml dependency gone asap.

**Comment by kba** [comment]
Nice thing about hachoir is that it's stream based so very efficient for reading just the metadata (PIL is too probably, just something to keep in mind for scalability).

**Comment by cneud** [comment]
I also thought of [Tika](https://tika.apache.org/) for streaming but for Python there are only Java bindings or calls to a Tika REST server.
