### ISSUE TITLE
Resource resolving not working for $PWD/ocrd-resources

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/core#727]
I have (due to some quick hack to check something) my models in a directory `$PWD/ocrd-resources`, according to the [docs](https://ocr-d.de/en/spec/ocrd_tool#file-parameters):

~~~
ocrd-resources
ocrd-resources/ocrd-calamari-recognize
ocrd-resources/ocrd-calamari-recognize/qurator-gt4histocr-1.0
ocrd-resources/ocrd-calamari-recognize/qurator-gt4histocr-1.0/3.ckpt.json
ocrd-resources/ocrd-calamari-recognize/qurator-gt4histocr-1.0/4.ckpt.h5
ocrd-resources/ocrd-calamari-recognize/qurator-gt4histocr-1.0/1.ckpt.h5
ocrd-resources/ocrd-calamari-recognize/qurator-gt4histocr-1.0/0.ckpt.h5
ocrd-resources/ocrd-calamari-recognize/qurator-gt4histocr-1.0/2.ckpt.json
ocrd-resources/ocrd-calamari-recognize/qurator-gt4histocr-1.0/2.ckpt.h5
ocrd-resources/ocrd-calamari-recognize/qurator-gt4histocr-1.0/4.ckpt.json
ocrd-resources/ocrd-calamari-recognize/qurator-gt4histocr-1.0/1.ckpt.json
ocrd-resources/ocrd-calamari-recognize/qurator-gt4histocr-1.0/0.ckpt.json
ocrd-resources/ocrd-calamari-recognize/qurator-gt4histocr-1.0/3.ckpt.h5
~~~

`ocrd-calamari-recognize` fails to find these:

~~~
15:23:53.051 ERROR ocrd.ocrd-calamari-recognize.resolve_resource - Could not find resource 'qurator-gt4histocr-1.0' for executable 'ocrd-calamari-recognize'. Try 'ocrd resmgr download ocrd-calamari-recognize qurator-gt4histocr-1.0' to download this resource.
~~~

I believe that the code at https://github.com/OCR-D/core/blob/d4a853964ce468a2c0eb6be2004c15441fbd206f/ocrd_utils/ocrd_utils/os.py#L68 should read:

~~~
candidates.append(join(cwd, 'ocrd-resources', executable, fname))  # Added 'ocrd-resources', executable
~~~

I'm not submitting a PR because I don't know if there are other reasons for leaving out ` 'ocrd-resources', executable` here. 

(If I'm putting the models into `qurator-gt4histocr-1.0` instead of `ocrd-resources/ocrd-calamari-recognize/qurator-gt4histocr-1.0`, it works.)

**Comment by bertsky** [comment]
@mikegerber does that conclude the case for you?

**Comment by mikegerber** [comment]
> @mikegerber does that conclude the case for you?

I think so, but https://ocr-d.de/en/spec/ocrd_tool#file-parameters does not seem up to date yet? (My main issue is that the documentation does not match the behaviour)

**Comment by bertsky** [comment]
> I think so, but https://ocr-d.de/en/spec/ocrd_tool#file-parameters does not seem up to date yet? (My main issue is that the documentation does not match the behaviour)

Indeed: that's still the old version. https://github.com/OCR-D/spec/blob/master/ocrd_tool.md#file-parameters has it right, so the website needs to be updated. (And we should probably notify users via Gitter, even if the implemented behaviour has not changed.)

**Comment by kba** [comment]
> I think so, but https://ocr-d.de/en/spec/ocrd_tool#file-parameters does not seem up to date yet? (My main issue is that the documentation does not match the behaviour)

Yes, there was an issue with the publishing workflow for the specs, has been fixed and site has been updated.

> (And we should probably notify users via Gitter, even if the implemented behaviour has not changed.)

[done](https://gitter.im/OCR-D/Lobby?at=619e7e0963c1e83c9527d954)
