### ISSUE TITLE
Missing six requirement for ocrd_models

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/core#730]
b8e7b683 introduced a dependency on [six](https://pypi.org/project/six/) but ocrd_models [does not require it in requirements.txt](https://github.com/OCR-D/core/blob/master/ocrd_models/requirements.txt).

No idea why I noticed this today due to a failing build. Maybe something else pulled six in before.

**Comment by kba** [comment]
https://github.com/OCR-D/core/pull/732 should fix the problem @mikegerber @hnesk

**Comment by mikegerber** [comment]
Looks good (but I didn't test it)
