### ISSUE TITLE
Increase PIL.Image.MAX_IMAGE_PIXELS

### ISSUE THREAD

**Issue by kba** [OCR-D/core#735]
By default, PIL has a maximum number of pixels of 89478485, i.e. a square image of 9500 pixels. Large high-resolution newspaper scans can be larger than that. @mittagessen increased this to accomodate up to 20,000 by 20,000 pixels in kraken, which seems reasonable and we should probably do the same.

**Comment by stweil** [comment]
Tesseract has an [open issue](https://github.com/tesseract-ocr/tesseract/issues/3184) because it is limited to 32767 x 32767 pixels. So maybe the proposed new limit here is still too small.

**Comment by kba** [comment]
> Tesseract has an [open issue](https://github.com/tesseract-ocr/tesseract/issues/3184) because it is limited to 32767 x 32767 pixels. So maybe the proposed new limit here is still too small.

Fine by me, but we need to keep this in mind when transitioning to HTTP interfaces, lest malicious API clients use this for DOS attacks.

**Comment by stweil** [comment]
That's right. As large images are usually rectangles (not squares) and the crucial point in DOS attacks is the memory usage, limiting the total number of pixels  to something lower than the x, y limits might also be acceptable.

Perhaps it is also necessary to have limits which can be configured to match the available computing resources.

I already experience such (unexpected) limits with Calamari and Kraken training (more than 64 GiB RAM for commonly used training data sets) and Dinglehopper (30 GiB RAM with two text files of about 3000 lines each).
