### ISSUE TITLE
bashlib: fix make lib.bash dependencies

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#742]
IMHO it's crazy we need (a recent version of) nodejs and its packagers to rebuild bashlib. If we do require non-bash functionality, then why not rely on Python here?

Also, the recipe https://github.com/OCR-D/core/blob/d9f660ee727c5235813e7f1534e26f2bebe483d3/ocrd/bashlib/Makefile#L16-L17 is dangerous, as it creates an (empty) result even in the case of errors (and thus prevents further updates to the target). (If using a shell redirect, the makefile should at least contain `.DELETE_ON_ERROR`.)

**Comment by kba** [comment]
When I started on bashlib, I was doing a lot of Node.JS and was very enamoured with my shell-based tools (shinclude, shrender, tesht etc.) and OCR-D/core was still to be a reference implementation that people might or might not use, so I didn't really take into account how easy it is for others to work with it.

I think we should just drop the shinclude mechanism and have a single big `lib.bash` file that we work on directly.

As for Node.JS: You only need that for regenerating the `make help` output (by way of `@kba/makefile-parser`) and for the continuous building of lib.bash on file change - which we wouldn't need anymore.
