### ISSUE TITLE
Workspace validator stricter than the specs

### ISSUE THREAD

**Issue by mweidling** [OCR-D/core#844]
The specs for `fileGrp/@USE` state that file groups `SHOULD` have a prefix `OCR-D`, but it is completely optional.

However, the workspace validator requires it at https://github.com/OCR-D/core/blob/master/ocrd_validators/ocrd_validators/workspace_validator.py#L244:

```python
            if not fileGrp.startswith(FILE_GROUP_PREFIX):
                self.report.add_notice("fileGrp USE does not begin with '%s': %s" % (FILE_GROUP_PREFIX, fileGrp))
```

where `FILE_GROUP_PREFIX` is `OCR-D-`.

This check probably has to be removed.

**Comment by mweidling** [comment]
Ah, I misread. My bad.

**Comment by kba** [comment]
also, you can skip that validation with the `--skip mets_file_group_names` option to `ocrd workspace validate`.
