### ISSUE TITLE
ocrd-tool.json validator: too strict

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#848]
In our ocrd-tool schema, for the parameters we only have https://github.com/OCR-D/core/blob/ecdb840dcfd972fcf1ad63c99bf724b0e89bc9fa/ocrd_validators/ocrd_validators/ocrd_tool.schema.yml#L62-L90

This excludes perfectly sound data JSON qualifiers like
- `items` (for restrictions on the list items if `type==array`)
- `minimum`, `maximum`, `exclusiveMinimum`, `exclusiveMaximum`, `multipleOf` (for numerical restrictions if `type==number`)
- fileGrp names not conforming to `^OCR-D-[A-Z0-9-]+$` (which should be allowed by spec now)

The first two yield an error saying `Additional properties are not allowed`, the latter directly mocks the regex.

**Comment by bertsky** [comment]
Perhaps also:
- `properties` and `additionalProperties` (for key-val restrictions on the entries if `type==object`)

**Comment by kba** [comment]
Newest release allows all these additional JSON-Schema constructs.

**Comment by bertsky** [comment]
> > Perhaps also:
> > 
> > * `properties` and `additionalProperties` (for key-val restrictions on the entries if `type==object`)

> Newest release allows all these additional JSON-Schema constructs.

Not all, it seems:

```
<report valid="false">
  <error>[tools.ocrd-kraken-segment.parameters.blla_classes] Additional properties are not allowed ('minProperties' was unexpected)</error>
  <error>[tools.ocrd-kraken-segment.parameters.blla_classes.additionalProperties] {'type': 'string', 'enum': ['TextRegion', 'ImageRegion', 'LineDrawingRegion', 'GraphicRegion', 'TableRegion', 'ChartRegion', 'MapRegion', 'SeparatorRegion', 'MathsRegion', 'ChemRegion', 'MusicRegion', 'AdvertRegion', 'NoiseRegion', 'UnknownRegion', 'CustomRegion']} is not of type 'boolean'</error>
</report>
```

Can we get this to work, or should I create another issue, @kba?
