### ISSUE TITLE
OcrdMets.find_files: allow regex for pageId, or orderlabel ranges

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#855]
If you want to process a range of pages, but the physical page IDs are not completely homogeneous (i.e. you have variation in both the alphabetic and numeric parts of the identifiers), then the current numerical page range syntax does not help.

But `find_files` does not allow the `//` prefix notation for regular expressions either:
```
find_files does not support regex search for pageId
```

Why not, actually?

As an alternative, one could allow passing the purely numerical index or the structMap's `@ORDERLABEL`, too.

**Comment by kba** [comment]
> Why not, actually?

Because we didn't want to do the pageId look-up for every single file. But then we implemented the pageIds being retrieved more efficiently with a single xpath. So, there is now indeed no reason not to support regex for pageId.
