### ISSUE TITLE
ocrd_utils.safe_filename: replace . with _

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#858]
For automatic file ID creation in various places, core uses `ocrd_utils.safe_filename`. However, this currently does not give dots any special consideration, which may yield IDs like `GN.1765.1.002.txt`. This often leads to problems downstream, because `.` is searched for in suffix detection, so the stem is not recognized.

**Comment by kba** [comment]
Agreed, `_` is a better replacement than `.`.
