### ISSUE TITLE
consistency of pageId kwarg name

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#862]
We currently have:
- `page_id` in all of `ocrd.*` (except `Workspace.add_file()`)
- `pageId` in all of `ocrd_models.*`

That is:
- `OcrdFile(...pageId...)`
- `OcrdMets.remove_file(...pageId...)`
- `OcrdMets.find_files(...pageId...)`
- `OcrdMets.add_file(...pageId...)`
- `Workspace.add_file(...pageId...)`

But:
- `Workspace.save_image_file(...page_id...)`
- `Workspace.image_from_page(...page_id...)`
- `Workspace.image_from_segment(...page_id...)`
- `Processor(...page_id...)`
- `processor.run_processor(...page_id...)`
- `processor.run_cli(...page_id...)`
- `task_sequence.validate_tasks(...page_id...)`

This is highly confusing, as one can see by the mistake I made myself here:
https://github.com/OCR-D/ocrd_segment/blob/5041b733a5058151b6c63fdb22264c1f2de25dae/ocrd_segment/extract_regions.py#L162-L175

I suggest to at least offer an **alias** `page_id` in the `ocrd.workspace` delegator to `OcrdMets` (and perhaps deprecate the `pageId` kwarg).

**Comment by kba** [comment]
I sometimes stumble upon that myself.

Agree to at least offer named aliases and deprecating the CamelCase variant for consistency.

**Comment by joschrew** [comment]
I have looked into this problem. What I would do is to rename any occurrence of `pageId` (154 matches!?) with `page_id` and add `@deprecated_alias` for all changed function definitions to make invocation with `pageId` still possible.
Is that what you had in mind or am I overshooting the mark here?

**Comment by kba** [comment]
> I have looked into this problem. What I would do is to rename any occurrence of `pageId` (154 matches!?) with `page_id` and add `@deprecated_alias` for all changed function definitions to make invocation with `pageId` still possible. Is that what you had in mind or am I overshooting the mark here?

In principle yes, but I would limit the renaming to those cases where `pageId` is a kwarg, i.e. those that @bertsky lists above. For example, we **should not** rename the `pageId` property of `OcrdFile`.

**Comment by bertsky** [comment]
> > I have looked into this problem. What I would do is to rename any occurrence of `pageId` (154 matches!?) with `page_id` and add `@deprecated_alias` for all changed function definitions to make invocation with `pageId` still possible. Is that what you had in mind or am I overshooting the mark here?
> 
> In principle yes, but I would limit the renaming to those cases where `pageId` is a kwarg, i.e. those that @bertsky lists above. For example, we **should not** rename the `pageId` property of `OcrdFile`.

IMHO we can stay with `pageId` for `ocrd_models` and `page_id` for `ocrd` API and CLI. There is currently only one exception to that rule.

(Perhaps we should also offer `Workspace.find_files` as a delegator to `OcrdMets.find_files` _and_ translator of `file_grp|file_id|page_id` to `fileGrp|ID|pageId`)
