### ISSUE TITLE
ocrd workspace add: Show full help when calling without arguments

### ISSUE THREAD

**Issue by VolkerHartmann** [OCR-D/core#91]
Usage prints no Options:
 > ocrd workspace add
Usage: ocrd workspace add [OPTIONS] LOCAL_FILENAME

Error: Missing argument "local_filename".

**Comment by kba** [comment]
```
ocrd workspace add --help
```

**Comment by VolkerHartmann** [comment]
Kling logisch aber das steht ja bei der Usage auch nicht dabei. ;-)

**Comment by kba** [comment]
Technically, `--help` and `--usage` are options, so they're implied in `OPTIONS`.

But sure, we should improve the user experience here later. `--help` is hopefully a convention used widely enough for people to try it for the time being.

**Comment by kba** [comment]
It's possible to do that (show help if required arguments are missing) but it's arguably not ideal to have the full help page every time you mistype. `--help` works for all commands/subcommands always.
