### ISSUE TITLE
Replace "pyocrd"

### ISSUE THREAD

**Issue by kba** [OCR-D/core#93]
Still used in some constants and filenames such as tempfile names.

**Comment by cneud** [comment]
This will require some reviewing https://github.com/cneud/core/commit/a402530253c4f2526b41fbd7585671354527af25

**Comment by kba** [comment]
I hesitated with implementing this because `pyocrd` is unique and easily identifiable. Replacing it with `core` makes it harder to spot temporary files and to grep. The real question is whether there is a better replacement than just `core`.

**Comment by cneud** [comment]
Indeed, I stumbled upon this also during refactoring. `ocrd-core` or simply just `ocrd` might also work, but neither of them strikes me as particularly pretty...

**Comment by cneud** [comment]
[Updated](https://github.com/cneud/core/commit/db7966cee77de8cf91f3e9da23f50dffd0923ab3) to current ``core``, changes look harmless to me?

**Comment by kba** [comment]
Yup, open a PR and I'll merge it.
