### ISSUE TITLE
Error when running processing server with ocrd-tesserocr

### ISSUE THREAD

**Issue by joschrew** [OCR-D/core#942]
Hi, I came across this error when experimenting with the mentioned [processing-server pull request](https://github.com/OCR-D/core/pull/884) , but think it could appear without the PR too.
Error message:
```
  File "/home/jschrew/loeschmich/core-pr/ocrd/ocrd/processor/helpers.py", line 227, in run_processor_from_api
    input_file_grp=input_file_grps_str, output_file_grp=output_file_grps_str)
  File "/home/jschrew/loeschmich/core-pr/ocrd/ocrd/processor/helpers.py", line 88, in run_processor
    processor = get_processor(parameter, processorClass)
  File "/home/jschrew/loeschmich/core-pr/ocrd/ocrd/processor/helpers.py", line 252, in wrapped
    return func(*args, **kwargs)
  File "/home/jschrew/loeschmich/core-pr/ocrd/ocrd/processor/helpers.py", line 273, in get_processor
    return processor_class(workspace=None, parameter=dict_params)
  File "/home/jschrew/loeschmich/ocrd_tesserocr/ocrd_tesserocr/segment_region.py", line 31, in __init__
    self.recognizer = TesserocrRecognize(self.workspace, **recognize_kwargs)
  File "/home/jschrew/loeschmich/ocrd_tesserocr/ocrd_tesserocr/recognize.py", line 135, in __init__
    super(TesserocrRecognize, self).__init__(*args, **kwargs)
TypeError: __init__() got multiple values for argument 'workspace'
```

This is what I did to get the error:

Take the Processing-Server-PR and merge the latest ocrd (2.40). Then I installed that to a venv and installd ocrd-tesserocr there as well (when installing the requirements.txt I removed the first line to keep the pull-request installation of ocrd-core). Then I start a mongodb on localhost:27018 and run the server with `ocrd-tesserocr-segment-region --address "0.0.0.0:5050:mongodb://localhost:27018/ocrd"`.
Then I wanted to use the processing server with curl: `curl -X POST localhost:5050/ -H "Content-Type: application/json" -d '{"path": "/tmp/workspaces/test1/mets.xml", "input_file_grps": ["OCR-D-SEG-PAGE"], "output_file_grps": ["OCR-D-SEG-BLOCK"]}'`. I have a test-workspace set up with all required file-grps existing in `/tmp/workspace/test1/`.

I guess the problem is the following:
The processing server first initializes the processor with this line `return processor_class(workspace=None, parameter=dict_params)` in ocrd/ocrd/processor/helpers.py. This causes the constructor of `TesserocrSegmentRegion` in segment_region.py to provide the workspace-Argument twice to its "SubProcessor" (`TesserocrRecognize`) as a arg at position 1 and additionally as a kwarg.

**Comment by bertsky** [comment]
This was addressed by https://github.com/OCR-D/ocrd_tesserocr/pull/191
