### ISSUE TITLE
Resource manager should support ZIP files as well as tarballs

### ISSUE THREAD

**Issue by kba** [OCR-D/core#963]
> Downloading https://layoutlm.blob.core.windows.net/docbank/model_zoo/X101.zip to download.tar.xx

@kba it seems that zip files have never been supported in resmgr to date. Should I open an issue?

_Originally posted by @bertsky in https://github.com/bertsky/ocrd_detectron2/issues/15#issuecomment-1337795992_

**Comment by bertsky** [comment]
Fixed via #967
