### ISSUE TITLE
workspace download: add retry option

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#973]
> Currently, the `find` command of the `Workspace` has a `--download` and `--wait` options. Do you see any potential issues if we provide an extra option that could retry downloading a file if the initial try fails? Something like:
> 
> ```python
> @click.option('--retry-times', type=int, default=0, help="Try this many times if a download request fails")
> ```
> 
> Some METS files inside VD18 repository of SUB contain host links that sometimes fail randomly if many files are retrieved back to back. No matter how much waiting time I put between the requests it would still randomly fail on some file. I know this is a problem on the SUB side, but it's unknown to me how many METS files do they have in that state. So the suggested change above, should at least, give a bit more flexibility. Trying once or twice more (which seems to solve the problem) should also take less time than waiting few seconds between the requests.
> 
> Since the downloading happens in a loop if a file is missing and the download fails, e.g., with `Exception: HTTP request failed: URL (HTTP 500)` - the process is terminated with failure. I have tracked the execution path. There is a method `Workspace.download_file` which internally calls `Resolver.download_to_directory` which triggers that exception if the response status code is not `200`. But since I am confused with the argument `_recursion_count` of `Worksapce.download_file` I did not spent more time to understand the logic.

_originally [posted](https://github.com/OCR-D/core/pull/966#issuecomment-1398341131) by @MehmedGIT_

**Comment by bertsky** [comment]
I completely second that.

BTW the `_recursion_count` serves a different purpose: 
https://github.com/OCR-D/core/blob/c75e219b45ef834e0a2c7592527b9a5af1f8c213/ocrd/ocrd/workspace.py#L177-L178

So for **relative paths** we first try to resolve directly, then try to prepend a URL prefix.

**Comment by MehmedGIT** [comment]
@bertsky Thanks, for creating the issue and clarifying the parameter. I understand now and to me it feels like a fast hack to achieve the desired behaviour with less code.

**Comment by bertsky** [comment]
> I understand now and to me it feels like a fast hack to achieve the desired behaviour with less code.

AFAICT it's a different beast. The `baseurl` prepend logic applies to the state of affairs when you have a freshly cloned workspace (whether from a local source directory or URL) – before downloading the content files. Any relative references must then be rebased from the source
