### ISSUE TITLE
Usage of 'ocrd ocrd-tools tool' is wrong

### ISSUE THREAD

**Issue by VolkerHartmann** [OCR-D/core#98]
The JSON-File is missing for the Usage:
```
> ocrd ocrd-tool tool --help
Usage: ocrd ocrd-tool tool [OPTIONS] TOOL_NAME COMMAND [ARGS]...
```

**Comment by kba** [comment]
Overriding the `Usage: ` string in click is surprisingly difficult. After browsing the source for a while and trying a few things (`subcommand_metavar` came close but no cigar), I give up on this for now. I'm sure there is a way but it will require hard-coding text that might change and I'd like to avoid that before we're settled on the syntax.

BTW: If you have an idea for a less palindromatic syntax, I'm open for suggestions, `ocrd ocrd-tool tool` is a bit silly.

**Comment by kba** [comment]
It's confusing if you're new to it but at least it's consistent for all subcommands. I think we can live with this behavior.
