### ISSUE TITLE
ocrd from pypi: failed to find magic

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#982]
I get…

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/magic/__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
  File "/usr/local/lib/python3.6/dist-packages/magic/loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

I already got `imagemagick` from apt and `magick` from pip. Seems we now need some additional library. I thought we made this optional (for casual users who don't enter via our Makefile's `deps-ubuntu`)?

**Comment by bertsky** [comment]
Ah, that's not related to IM, but `libmagic-dev`, which we now need for MIME type guessing:

https://github.com/OCR-D/core/blob/ee92cfc084b8e4f2dd5be2f7016f957c87ae1573/ocrd/ocrd/resource_manager.py#L320

**Comment by bertsky** [comment]
Why don't we just trust our EXT_TO_MIME rules here?

**Comment by bertsky** [comment]
How about the (dep-free) Python pkg [filetype](https://pypi.org/project/filetype/)?

(For suffix based detection, how about also conferring builtin [mimetypes](https://docs.python.org/3/library/mimetypes.html)?)

**Comment by kba** [comment]
> https://storage.googleapis.com/drive-bulk-export-anonymous/20230310T105258.886+0000/4133399871716478688/ffca26bf-0e9c-4e1a-8757-395da4fb2a80/1/d8dffe73-127e-4ce7-8ebf-7c95f9220783?authuser

I'm getting a 403 for that, what HTTP headers does it return for you, esp. `Content-Type`? Then we could use that info.

But yes, https://github.com/h2non/filetype.py looks like a good  dependency-free alternative, I'll investigate.

**Comment by bertsky** [comment]
> I'm getting a 403 for that,

sry, that was a short-lived URL, too. (New version: try [this](https://doc-0k-44-docs.googleusercontent.com/docs/securesc/96244tehjocb7kc01p0miuo7l4lmt7ch/6h7arfl8qj814o3uhgmvfl7ps4jhnbku/1678701750000/00428462094679908272/16853707297506473473/11FgFTy0MyVUMGd00T_InEDaarB4qAlP8?ax=AB85Z1ASPJWelvHYGQmDDD5A_15sZHa-fyuzDbf6GdAOJxcRWvZYSj3SbAVcZB_8sN5zoq8_qraxtLTnr86UTg-Vs58mjXsrHdyd21nbqwMIcRmNx6XDNNvOD3oy_fVS7M5iEMAhGq59PJ0MJ7Zy1SFn5ufwdrEmTqJnSWOkeIqgAWcsvUBoXnTuwmWhd5amfIgFoxNL4_8kimll_M6Sc5I_bRapqCRggEvhglyceyNo91X6euJUnJcklMJ5t9MAIWfbGgmMI1njM5w_UYJDW8COsoNR3Puc624IyC_-Q-n5PCrnq9AWR9ZMcVLFtfEp33nDwCxltXkqvJh7ObAukf1d-BOnGz9WJbSwEHA67gwYbJe0R6l-1KrgVqtfWNgwcChRgWaSjkdosZB07QBDY5zbGVALvHN29JSY-N5xGx5BZQaJSf8GKobwyLjjzbb50-NG4E6Yr1chZ-hPfgTFIYPnfPsZP1aMZRUDZuXj0BRDUXHWE1_gxKHdqayfDTaBJ83NAfXTPyBV34b6rAsWafYwJvXjlwu9Nw8yEPcSXzH3aPHC5jW69NYn9LmeTSe2V8K3wlCwkEo-GY5LOHanqhMTmCkoAJrsjhH4dSGjKRvsgx0m_2vAiLmqRvpjTzvK8Iu639KtSjwc7wm-_MGzVpF4VdyAzQvcb0fv7xWfEDRHn9HMu79bbcgT_q_hnlSppJqJoSQuF38U4j9LZbLxXmo5WQLl2pW94xGcndNOQEr9c1qmQMWoNa0sRpd1ngCMqBoTm5L0iU2JVgzDTKpOUUo7G7xFvzBJM0wWEGGfDYzZ3oQ_41zikrdhRtg3tG8n8fzFbXpKZSTZwbEyDHhPi00B4XXwzVIKOEhlS7Per1_XBNE6WBz7SzfFxHOqbWbjb_iiEw&uuid=54c8d292-27b9-4bad-9ce8-134e18499bcc&authuser=0&nonce=ths2ljvkhm6ji&user=16853707297506473473&hash=odt38ede484kgvjqrfdksp351duov6i7)

For this example the correct (albeit non-direct) URL is here: https://github.com/bertsky/ocrd_detectron2/blob/e005d3cfd6ff88bc8a195d0968c9ba8d8ada6b0b/ocrd_detectron2/ocrd-tool.json#L89

> hat HTTP headers does it return for you, esp. `Content-Type`?

If you follow Google's protocoll (as gdown does), you'll end up with
```
'Content-Type': 'application/octet-stream', 
'Content-Disposition': 'attachment; filename="model_final.pth"
```
So that does not help.
