### ISSUE TITLE
Docker build: opencv-python-headless fails

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#983]
Our last Docker release is now 9 months old. It seems there is a [persistent error](https://app.circleci.com/pipelines/github/OCR-D/core/1581/workflows/58b2759d-e91c-4c57-a720-b1686f64e261/jobs/5574) around the OpenCV Build:
```
ERROR: Failed building wheel for opencv-python-headless
```

Perhaps Python 3.6 is not supported anymore (no wheels on PyPI)? Or do we need more [system dependencies](https://docs.opencv.org/4.x/d2/de6/tutorial_py_setup_in_ubuntu.html) now?

**Comment by bertsky** [comment]
@kba your [CI config change](https://github.com/OCR-D/core/commit/27427e22116eb0a866c79dc87c5435c08146a0dd) still does not work on the Scrutinizer chain – it for some reason needs `sudo` for `make deps-ubuntu`. Also, on `master` we [fail to deploy](https://app.circleci.com/pipelines/github/OCR-D/core/1605/workflows/6eeae1ef-a008-4163-9b58-9d8570852a3f/jobs/5705) awkwardly:
```
/bin/sh: 1: pip: not found
The command '/bin/sh -c apt-get update && apt-get -y install software-properties-common     && apt-get update && apt-get -y install         ca-certificates         python3-dev         python3-pip         gcc         make         wget         time         curl         sudo         git     && make deps-ubuntu     && pip install --upgrade pip setuptools     && make install     && apt-get remove -y gcc     && apt-get autoremove -y     && $FIXUP     && rm -rf /build-ocrd' returned a non-zero code: 127
Makefile:217: recipe for target 'docker-cuda' failed
```

So `make docker` runs through, but `docker-cuda` does not.

Regarding the original error reported here – that seems to have been specific to 3.6 (and I believe it would suffice to do a simple `pip install -U pip` first, to get `pip install cmake` working; so we could even reactivate our 3.6 CI...)

**Comment by mikegerber** [comment]
I've been using this sometimes:

```
pip3 install -U pip
pip3 install --only-binary :all: opencv-python-headless
```

This installs an older opencv-python-headless, but from a wheel and without the compile time. I'd recommend always testing anything involving opencv-python-headless, we had some [tricky issues with it](https://github.com/qurator-spk/sbb_textline_detection/issues/60).

**Comment by bertsky** [comment]
We did introduce a [workaround in ocrd_all](https://github.com/OCR-D/core/commit/5779122857dd0cf2e3eb2d2f0629b3be97d4798f) earlier to avoid source compilation (which effectively downgrades, but also speeds up). This warrants closing – also, 3.6 is not officially supported anymore.
